---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/26 0026 22:33
---

--GameObject = CS.UnityEngine.GameObject;
--StringBuilder = CS.System.Text.StringBuilder;
--local a = GameObject();
--print(a.name);
--
--local b = StringBuilder();
--b:Append("abc");
--print(b:ToString());

require "DrbFrameworkEntry";

DrbFrameworkEntry.Init();