---@class zlibConst
---@field public Z_NO_COMPRESSION number
---@field public Z_BEST_SPEED number
---@field public Z_BEST_COMPRESSION number
---@field public Z_DEFAULT_COMPRESSION number
---@field public Z_FILTERED number
---@field public Z_HUFFMAN_ONLY number
---@field public Z_DEFAULT_STRATEGY number
---@field public Z_NO_FLUSH number
---@field public Z_PARTIAL_FLUSH number
---@field public Z_SYNC_FLUSH number
---@field public Z_FULL_FLUSH number
---@field public Z_FINISH number
---@field public Z_OK number
---@field public Z_STREAM_END number
---@field public Z_NEED_DICT number
---@field public Z_ERRNO number
---@field public Z_STREAM_ERROR number
---@field public Z_DATA_ERROR number
---@field public Z_MEM_ERROR number
---@field public Z_BUF_ERROR number
---@field public Z_VERSION_ERROR number
---@public
---@return string
function zlibConst.version() end
