---@class Timer
---@field public onStart OnStartHandler
---@field public onUpdate OnUpdateHandler
---@field public onComplete OnCompleteHandler
---@field public IsRunning bool
---@field public IsDelaying bool
---@field public CurrentLoop number
---@field public DelayTime number
---@field public Interval number
---@field public Loop number
---@public
---@return void
function Timer:Pause() end
