---@class BraceStyle : Enum
---@field public value__ number
---@field public EndOfLine number
---@field public EndOfLineWithoutSpace number
---@field public NextLine number
---@field public NextLineShifted number
---@field public NextLineShifted2 number
