---@class BraceForcement : Enum
---@field public value__ number
---@field public DoNotChange number
---@field public RemoveBraces number
---@field public AddBraces number
---@field public RemoveBracesForSingleLine number
