---@class LocalLookupVariable
---@field public Name string
---@field public TypeRef TypeReference
---@field public StartPos Location
---@field public EndPos Location
---@field public IsConst bool
---@field public IsLoopVariable bool
---@field public Initializer Expression
---@field public ParentLambdaExpression LambdaExpression
---@field public IsQueryContinuation bool
