---@class SnippetType : Enum
---@field public value__ number
---@field public None number
---@field public CompilationUnit number
---@field public Expression number
---@field public Statements number
---@field public TypeMembers number
