---@class ImplicitUseKindFlags : Enum
---@field public value__ number
---@field public Default number
---@field public Access number
---@field public Assign number
---@field public InstantiatedWithFixedConstructorSignature number
---@field public InstantiatedNoFixedConstructorSignature number
