---@class ImplicitUseTargetFlags : Enum
---@field public value__ number
---@field public Default number
---@field public Itself number
---@field public Members number
---@field public WithMembers number
