---@class Win32ResultCode
---@field public Success number
---@field public FileNotFound number
---@field public AccessDenied number
---@field public InvalidParameter number
---@field public MoreData number
---@field public NetworkPathNotFound number
---@field public NoMoreEntries number
---@field public MarkedForDeletion number
