---@class GenericInstanceType : TypeSpecification
---@field public HasGenericArguments bool
---@field public GenericArguments Collection`1
---@field public DeclaringType TypeReference
---@field public FullName string
---@field public IsGenericInstance bool
---@field public ContainsGenericParameter bool
