---@class DTDAttributeOccurenceType : Enum
---@field public value__ number
---@field public None number
---@field public Required number
---@field public Optional number
---@field public Fixed number
