---@class GenericInstanceMethod : MethodSpecification
---@field public HasGenericArguments bool
---@field public GenericArguments Collection`1
---@field public IsGenericInstance bool
---@field public ContainsGenericParameter bool
---@field public FullName string
