---@class SequencePoint
---@field public Offset number
---@field public StartLine number
---@field public StartColumn number
---@field public EndLine number
---@field public EndColumn number
---@field public IsHidden bool
---@field public Document Document
