---@class XsdString : XsdAnySimpleType
---@field public TokenizedType number
---@field public TypeCode number
---@field public ValueType Type
---@field public Bounded bool
---@field public Finite bool
---@field public Numeric bool
---@field public Ordered number
