---@class AsyncMethodBodyDebugInformation : CustomDebugInformation
---@field public KindIdentifier Guid
---@field public CatchHandler InstructionOffset
---@field public Yields Collection`1
---@field public Resumes Collection`1
---@field public MoveNextMethod MethodDefinition
---@field public Kind number
