---@class DTDEntityBase : DTDNode
---@field public LoadFailed bool
---@field public Name string
---@field public PublicId string
---@field public SystemId string
---@field public LiteralEntityValue string
---@field public ReplacementText string
---@field public XmlResolver XmlResolver
---@field public ActualUri string
---@public
---@return void
function DTDEntityBase:Resolve() end
