---@class ConfidenceFactor : Enum
---@field public value__ number
---@field public ExtraLow number
---@field public Low number
---@field public Medium number
---@field public High number
---@field public ExtraHigh number
---@field public Provable number
