---@class DTDElementDeclaration : DTDNode
---@field public Name string
---@field public IsEmpty bool
---@field public IsAny bool
---@field public IsMixedContent bool
---@field public ContentModel DTDContentModel
---@field public Attributes DTDAttListDeclaration
