---@class ClientCertificateType : Enum
---@field public value__ number
---@field public RSA number
---@field public DSS number
---@field public RSAFixed number
---@field public DSSFixed number
---@field public Unknown number
