---@class X509StoreManager
---@field public CurrentUser X509Stores
---@field public LocalMachine X509Stores
---@field public IntermediateCACertificates X509CertificateCollection
---@field public IntermediateCACrls ArrayList
---@field public TrustedRootCertificates X509CertificateCollection
---@field public TrustedRootCACrls ArrayList
---@field public UntrustedCertificates X509CertificateCollection
