---@class OpCodeType : Enum
---@field public value__ number
---@field public Annotation number
---@field public Macro number
---@field public Nternal number
---@field public Objmodel number
---@field public Prefix number
---@field public Primitive number
