---@class PKCS5
---@field public pbeWithMD2AndDESCBC string
---@field public pbeWithMD5AndDESCBC string
---@field public pbeWithMD2AndRC2CBC string
---@field public pbeWithMD5AndRC2CBC string
---@field public pbeWithSHA1AndDESCBC string
---@field public pbeWithSHA1AndRC2CBC string
