---@class SymbolKind : Enum
---@field public value__ number
---@field public NativePdb number
---@field public PortablePdb number
---@field public EmbeddedPortablePdb number
---@field public Mdb number
