---@class ExceptionHandler
---@field public TryStart Instruction
---@field public TryEnd Instruction
---@field public FilterStart Instruction
---@field public HandlerStart Instruction
---@field public HandlerEnd Instruction
---@field public CatchType TypeReference
---@field public HandlerType number
