---@class ArrayType : TypeSpecification
---@field public Dimensions Collection`1
---@field public Rank number
---@field public IsVector bool
---@field public IsValueType bool
---@field public Name string
---@field public FullName string
---@field public IsArray bool
