---@class DTDObjectModel
---@field public AllowedExternalEntitiesMax number
---@field public BaseURI string
---@field public IsStandalone bool
---@field public Name string
---@field public NameTable XmlNameTable
---@field public PublicId string
---@field public SystemId string
---@field public InternalSubset string
---@field public InternalSubsetHasPEReference bool
---@field public LineNumber number
---@field public LinePosition number
---@field public XmlResolver XmlResolver
---@field public Factory DTDAutomataFactory
---@field public RootElement DTDElementDeclaration
---@field public ElementDecls DTDElementDeclarationCollection
---@field public AttListDecls DTDAttListDeclarationCollection
---@field public EntityDecls DTDEntityDeclarationCollection
---@field public PEDecls DTDParameterEntityDeclarationCollection
---@field public NotationDecls DTDNotationDeclarationCollection
---@field public RootAutomata DTDAutomata
---@field public Empty DTDEmptyAutomata
---@field public Any DTDAnyAutomata
---@field public Invalid DTDInvalidAutomata
---@field public Errors XmlSchemaException[]
---@public
---@param name string
---@return string
function DTDObjectModel:ResolveEntity(name) end
---@public
---@param ex XmlSchemaException
---@return void
function DTDObjectModel:AddError(ex) end
