---@class AssemblyAttributes : Enum
---@field public value__ number
---@field public PublicKey number
---@field public SideBySideCompatible number
---@field public Retargetable number
---@field public WindowsRuntime number
---@field public DisableJITCompileOptimizer number
---@field public EnableJITCompileTracking number
