---@class Platform : Enum
---@field public value__ number
---@field public AnyCPU number
---@field public AnyCPU32Preferred number
---@field public Arm number
---@field public X86 number
---@field public X64 number
---@field public IA64 number
