---@class TargetArchitecture : Enum
---@field public value__ number
---@field public I386 number
---@field public AMD64 number
---@field public IA64 number
---@field public ARM number
---@field public ARMv7 number
---@field public ARM64 number
