---@class IGenericParameterProvider
---@field public HasGenericParameters bool
---@field public IsDefinition bool
---@field public Module ModuleDefinition
---@field public GenericParameters Collection`1
---@field public GenericParameterType number
