---@class PropertyAttributes : Enum
---@field public value__ number
---@field public None number
---@field public SpecialName number
---@field public RTSpecialName number
---@field public HasDefault number
---@field public Unused number
