---@class Document : DebugInformation
---@field public Url string
---@field public Type number
---@field public HashAlgorithm number
---@field public Language number
---@field public LanguageVendor number
---@field public Hash Byte[]
