---@class IMethodSignature
---@field public HasThis bool
---@field public ExplicitThis bool
---@field public CallingConvention number
---@field public HasParameters bool
---@field public Parameters Collection`1
---@field public ReturnType TypeReference
---@field public MethodReturnType MethodReturnType
