---@class XsdKeyEntryField
---@field public FieldFound bool
---@field public FieldLineNumber number
---@field public FieldLinePosition number
---@field public FieldHasLineInfo bool
---@field public FieldType XsdAnySimpleType
---@field public Identity Object
---@field public IsXsiNil bool
---@field public FieldFoundDepth number
---@field public FieldFoundPath XsdIdentityPath
---@field public Consuming bool
---@field public Consumed bool
---@field public Field XsdIdentityField
---@public
---@param identity Object
---@param isXsiNil bool
---@param type XsdAnySimpleType
---@param depth number
---@param li IXmlLineInfo
---@return bool
function XsdKeyEntryField:SetIdentityField(identity, isXsiNil, type, depth, li) end
