---@class Section
---@field public Name string
---@field public VirtualAddress number
---@field public VirtualSize number
---@field public SizeOfRawData number
---@field public PointerToRawData number
