---@class MethodDefinitionTreatment : Enum
---@field public value__ number
---@field public None number
---@field public Abstract number
---@field public Private number
---@field public Public number
---@field public Runtime number
---@field public InternalCall number
