---@class PropertyDefinition : PropertyReference
---@field public Attributes number
---@field public HasThis bool
---@field public HasCustomAttributes bool
---@field public CustomAttributes Collection`1
---@field public GetMethod MethodDefinition
---@field public SetMethod MethodDefinition
---@field public HasOtherMethods bool
---@field public OtherMethods Collection`1
---@field public HasParameters bool
---@field public Parameters Collection`1
---@field public HasConstant bool
---@field public Constant Object
---@field public IsSpecialName bool
---@field public IsRuntimeSpecialName bool
---@field public HasDefault bool
---@field public DeclaringType TypeDefinition
---@field public IsDefinition bool
---@field public FullName string
---@public
---@return PropertyDefinition
function PropertyDefinition:Resolve() end
