---@class TypeDefinitionProjection
---@field public Attributes number
---@field public Name string
---@field public Treatment number
---@field public RedirectedMethods Collection`1
---@field public RedirectedInterfaces Collection`1
