---@class ModuleAttributes : Enum
---@field public value__ number
---@field public ILOnly number
---@field public Required32Bit number
---@field public StrongNameSigned number
---@field public Preferred32Bit number
