---@class FieldDefinition : FieldReference
---@field public HasLayoutInfo bool
---@field public Offset number
---@field public RVA number
---@field public InitialValue Byte[]
---@field public Attributes number
---@field public HasConstant bool
---@field public Constant Object
---@field public HasCustomAttributes bool
---@field public CustomAttributes Collection`1
---@field public HasMarshalInfo bool
---@field public MarshalInfo MarshalInfo
---@field public IsCompilerControlled bool
---@field public IsPrivate bool
---@field public IsFamilyAndAssembly bool
---@field public IsAssembly bool
---@field public IsFamily bool
---@field public IsFamilyOrAssembly bool
---@field public IsPublic bool
---@field public IsStatic bool
---@field public IsInitOnly bool
---@field public IsLiteral bool
---@field public IsNotSerialized bool
---@field public IsSpecialName bool
---@field public IsPInvokeImpl bool
---@field public IsRuntimeSpecialName bool
---@field public HasDefault bool
---@field public IsDefinition bool
---@field public DeclaringType TypeDefinition
---@public
---@return FieldDefinition
function FieldDefinition:Resolve() end
