---@class ModuleParameters
---@field public Kind number
---@field public Runtime number
---@field public Timestamp Nullable`1
---@field public Architecture number
---@field public AssemblyResolver IAssemblyResolver
---@field public MetadataResolver IMetadataResolver
---@field public MetadataImporterProvider IMetadataImporterProvider
---@field public ReflectionImporterProvider IReflectionImporterProvider
