---@class SourceFile
---@field public Name string
---@field public FullPathName string
---@field public Index number
---@field public AutoGenerated bool
---@field public Checksum Byte[]
---@field public HasChecksum bool
---@public
---@param checksum Byte[]
---@return void
function SourceFile:SetChecksum(checksum) end
---@public
---@param algorithmGuid Byte[]
---@param checksum Byte[]
---@return void
function SourceFile:SetChecksum(algorithmGuid, checksum) end
---@public
---@param other SourceFile
---@return bool
function SourceFile:Equals(other) end
---@public
---@return string
function SourceFile:ToString() end
