---@class InterfaceImplementation
---@field public InterfaceType TypeReference
---@field public HasCustomAttributes bool
---@field public CustomAttributes Collection`1
---@field public MetadataToken MetadataToken
