---@class OptionalModifierType : TypeSpecification
---@field public ModifierType TypeReference
---@field public Name string
---@field public FullName string
---@field public IsValueType bool
---@field public IsOptionalModifier bool
---@field public ContainsGenericParameter bool
