---@class WriterParameters
---@field public Timestamp Nullable`1
---@field public SymbolStream Stream
---@field public SymbolWriterProvider ISymbolWriterProvider
---@field public WriteSymbols bool
---@field public StrongNameKeyPair StrongNameKeyPair
