---@class OutputMethod : Enum
---@field public value__ number
---@field public XML number
---@field public HTML number
---@field public Text number
---@field public Custom number
---@field public Unknown number
