---@class ReaderParameters
---@field public ReadingMode number
---@field public InMemory bool
---@field public AssemblyResolver IAssemblyResolver
---@field public MetadataResolver IMetadataResolver
---@field public MetadataImporterProvider IMetadataImporterProvider
---@field public ReflectionImporterProvider IReflectionImporterProvider
---@field public SymbolStream Stream
---@field public SymbolReaderProvider ISymbolReaderProvider
---@field public ReadSymbols bool
---@field public ReadWrite bool
---@field public ApplyWindowsRuntimeProjections bool
