---@class CustomAttribute
---@field public Constructor MethodReference
---@field public AttributeType TypeReference
---@field public IsResolved bool
---@field public HasConstructorArguments bool
---@field public ConstructorArguments Collection`1
---@field public HasFields bool
---@field public Fields Collection`1
---@field public HasProperties bool
---@field public Properties Collection`1
---@public
---@return Byte[]
function CustomAttribute:GetBlob() end
