---@class XsdDate : XsdAnySimpleType
---@field public TokenizedType number
---@field public TypeCode number
---@field public ValueType Type
---@field public Ordered number
---@public
---@param s string
---@param nameTable XmlNameTable
---@param nsmgr IXmlNamespaceResolver
---@return Object
function XsdDate:ParseValue(s, nameTable, nsmgr) end
