---@class CustomAttributeValueTreatment : Enum
---@field public value__ number
---@field public None number
---@field public AllowSingle number
---@field public AllowMultiple number
---@field public VersionAttribute number
---@field public DeprecatedAttribute number
