---@class SecurityAttribute
---@field public AttributeType TypeReference
---@field public HasFields bool
---@field public Fields Collection`1
---@field public HasProperties bool
---@field public Properties Collection`1
