---@class TypeReferenceTreatment : Enum
---@field public value__ number
---@field public None number
---@field public SystemDelegate number
---@field public SystemAttribute number
---@field public UseProjectionInfo number
