---@class DTDNotationDeclaration : DTDNode
---@field public Name string
---@field public PublicId string
---@field public SystemId string
---@field public LocalName string
---@field public Prefix string
