---@class StateMachineScopeDebugInformation : CustomDebugInformation
---@field public KindIdentifier Guid
---@field public Start InstructionOffset
---@field public End InstructionOffset
---@field public Kind number
