---@class ModuleCharacteristics : Enum
---@field public value__ number
---@field public HighEntropyVA number
---@field public DynamicBase number
---@field public NoSEH number
---@field public NXCompat number
---@field public AppContainer number
---@field public TerminalServerAware number
