---@class IMemberDefinition
---@field public Name string
---@field public FullName string
---@field public IsSpecialName bool
---@field public IsRuntimeSpecialName bool
---@field public DeclaringType TypeDefinition
