---@class ContentType : Enum
---@field public value__ number
---@field public ChangeCipherSpec number
---@field public Alert number
---@field public Handshake number
---@field public ApplicationData number
