---@class MethodReturnType
---@field public Method IMethodSignature
---@field public ReturnType TypeReference
---@field public MetadataToken MetadataToken
---@field public Attributes number
---@field public Name string
---@field public HasCustomAttributes bool
---@field public CustomAttributes Collection`1
---@field public HasDefault bool
---@field public HasConstant bool
---@field public Constant Object
---@field public HasFieldMarshal bool
---@field public HasMarshalInfo bool
---@field public MarshalInfo MarshalInfo
