---@class XsdIdentityStep
---@field public IsCurrent bool
---@field public IsAttribute bool
---@field public IsAnyName bool
---@field public NsName string
---@field public Name string
---@field public Namespace string
