---@class ImportTarget
---@field public Namespace string
---@field public Type TypeReference
---@field public AssemblyReference AssemblyNameReference
---@field public Alias string
---@field public Kind number
