---@class MSCompatUnicodeTableUtil
---@field public ResourceVersion number
---@field public Ignorable CodePointIndexer
---@field public Category CodePointIndexer
---@field public Level1 CodePointIndexer
---@field public Level2 CodePointIndexer
---@field public Level3 CodePointIndexer
---@field public CjkCHS CodePointIndexer
---@field public Cjk CodePointIndexer
