---@class ITestResult
---@field public ResultState ResultState
---@field public Name string
---@field public FullName string
---@field public Duration number
---@field public StartTime DateTime
---@field public EndTime DateTime
---@field public Message string
---@field public StackTrace string
---@field public AssertCount number
---@field public FailCount number
---@field public PassCount number
---@field public SkipCount number
---@field public InconclusiveCount number
---@field public HasChildren bool
---@field public Children IEnumerable`1
---@field public Test ITest
---@field public Output string
