---@class CommandStage : Enum
---@field public value__ number
---@field public Default number
---@field public BelowSetUpTearDown number
---@field public SetUpTearDown number
---@field public AboveSetUpTearDown number
