---@class RunState : Enum
---@field public value__ number
---@field public NotRunnable number
---@field public Runnable number
---@field public Explicit number
---@field public Skipped number
---@field public Ignored number
