---@class FrameworkPackageSettings
---@field public DebugTests string
---@field public PauseBeforeRun string
---@field public InternalTraceLevel string
---@field public WorkDirectory string
---@field public DefaultTimeout string
---@field public InternalTraceWriter string
---@field public LOAD string
---@field public NumberOfTestWorkers string
---@field public RandomSeed string
---@field public StopOnError string
---@field public SynchronousEvents string
---@field public DefaultTestNamePattern string
---@field public TestParameters string
