---@class FailureSite : Enum
---@field public value__ number
---@field public Test number
---@field public SetUp number
---@field public TearDown number
---@field public Parent number
---@field public Child number
