---@class RevisionClass
---@field public Major string
---@field public Minor string
---@field public Build string
---@field public Revision string
---@field public MainVersion string
---@field public FullVersion string
