---@class IGlobalConfiguration
---@field public AllowAttachedDebugging bool
---@field public ScriptDefaultApp string
---@field public PreviousScriptDefaultApp string
---@field public ScriptDefaultArgs string
