---@class IProjectConfiguration
---@field public IsUseOpenFileOverriden bool
---@field public IsSendConsoleToVisualStudioOverriden bool
---@field public IsRunInBackgroundOverriden bool
---@field public IsFileExtensionFilterOverriden bool
---@field public IsBuiltinExtensionFilterOverriden bool
---@field public IsGenerateSolutionFileOverriden bool
---@field public IsAnnounceEditorMulticastOverriden bool
---@field public IsRootNamespaceOverriden bool
