---@class ConfigurationFields
---@field public UseOpenFile ConfigurationField`1
---@field public SendConsoleToVisualStudio ConfigurationField`1
---@field public RunInBackground ConfigurationField`1
---@field public FileExtensionFilter ConfigurationField`1
---@field public GenerateSolutionFile ConfigurationField`1
---@field public AnnounceEditorMulticast ConfigurationField`1
---@field public RootNamespace ConfigurationField`1
