---@class XmlSchemaSimpleContentExtension : XmlSchemaContent
---@field public BaseTypeName XmlQualifiedName
---@field public Attributes XmlSchemaObjectCollection
---@field public AnyAttribute XmlSchemaAnyAttribute
