---@class FileShare : Enum
---@field public value__ number
---@field public None number
---@field public Read number
---@field public Write number
---@field public ReadWrite number
---@field public Delete number
---@field public Inheritable number
