---@class DeliveryNotificationOptions : Enum
---@field public value__ number
---@field public None number
---@field public OnSuccess number
---@field public OnFailure number
---@field public Delay number
---@field public Never number
