---@class CodeConditionStatement : CodeStatement
---@field public Condition CodeExpression
---@field public FalseStatements CodeStatementCollection
---@field public TrueStatements CodeStatementCollection
