---@class AssemblyNameFlags : Enum
---@field public value__ number
---@field public None number
---@field public PublicKey number
---@field public Retargetable number
---@field public EnableJITcompileOptimizer number
---@field public EnableJITcompileTracking number
