---@class DESCKIND : Enum
---@field public value__ number
---@field public DESCKIND_NONE number
---@field public DESCKIND_FUNCDESC number
---@field public DESCKIND_VARDESC number
---@field public DESCKIND_TYPECOMP number
---@field public DESCKIND_IMPLICITAPPOBJ number
---@field public DESCKIND_MAX number
