---@class ComCompatibleVersionAttribute : Attribute
---@field public MajorVersion number
---@field public MinorVersion number
---@field public BuildNumber number
---@field public RevisionNumber number
