---@class ConsoleScreenBufferInfo : ValueType
---@field public Size Coord
---@field public CursorPosition Coord
---@field public Attribute number
---@field public Window SmallRect
---@field public MaxWindowSize Coord
