---@class SectionData
---@field public SectionName string
---@field public TypeName string
---@field public AllowLocation bool
---@field public AllowDefinition number
---@field public FileName string
---@field public RequirePermission bool
