---@class RuntimeSecurityFrame
---@field public domain AppDomain
---@field public method MethodInfo
---@field public assert RuntimeDeclSecurityEntry
---@field public deny RuntimeDeclSecurityEntry
---@field public permitonly RuntimeDeclSecurityEntry
