---@class NativeOverlapped : ValueType
---@field public EventHandle IntPtr
---@field public InternalHigh IntPtr
---@field public InternalLow IntPtr
---@field public OffsetHigh number
---@field public OffsetLow number
