---@class HttpWebRequestElement : ConfigurationElement
---@field public MaximumErrorResponseLength number
---@field public MaximumResponseHeadersLength number
---@field public MaximumUnauthorizedUploadLength number
---@field public UseUnsafeHeaderParsing bool
