---@class Win32_FIXED_INFO
---@field public HostName string
---@field public DomainName string
---@field public CurrentDnsServer IntPtr
---@field public DnsServerList Win32_IP_ADDR_STRING
---@field public NodeType number
---@field public ScopeId string
---@field public EnableRouting number
---@field public EnableProxy number
---@field public EnableDns number
---@field public Instance Win32_FIXED_INFO
