---@class ConfigurationCollectionAttribute : Attribute
---@field public AddItemName string
---@field public ClearItemsName string
---@field public RemoveItemName string
---@field public CollectionType number
---@field public ItemType Type
