---@class CallbackValidatorAttribute : ConfigurationValidatorAttribute
---@field public CallbackMethodName string
---@field public Type Type
---@field public ValidatorInstance ConfigurationValidatorBase
