---@class EnvironmentPermissionAccess : Enum
---@field public value__ number
---@field public NoAccess number
---@field public Read number
---@field public Write number
---@field public AllAccess number
