---@class KeventData
---@field public FSW FileSystemWatcher
---@field public Directory string
---@field public FileMask string
---@field public IncludeSubdirs bool
---@field public Enabled bool
---@field public DirEntries Hashtable
---@field public ev kevent
