---@class SoapTypeAttribute : SoapAttribute
---@field public SoapOptions number
---@field public UseAttribute bool
---@field public XmlElementName string
---@field public XmlFieldOrder number
---@field public XmlNamespace string
---@field public XmlTypeName string
---@field public XmlTypeNamespace string
