---@class SerialError : Enum
---@field public value__ number
---@field public RXOver number
---@field public Overrun number
---@field public RXParity number
---@field public Frame number
---@field public TXFull number
