---@class XmlAttributeEventArgs : EventArgs
---@field public Attr XmlAttribute
---@field public LineNumber number
---@field public LinePosition number
---@field public ObjectBeingDeserialized Object
---@field public ExpectedAttributes string
