---@class UIPermissionWindow : Enum
---@field public value__ number
---@field public NoWindows number
---@field public SafeSubWindows number
---@field public SafeTopLevelWindows number
---@field public AllWindows number
