---@class SocketOptionLevel : Enum
---@field public value__ number
---@field public Socket number
---@field public IP number
---@field public IPv6 number
---@field public Tcp number
---@field public Udp number
