---@class SettingsProperty
---@field public Attributes SettingsAttributeDictionary
---@field public DefaultValue Object
---@field public IsReadOnly bool
---@field public Name string
---@field public PropertyType Type
---@field public Provider SettingsProvider
---@field public SerializeAs number
---@field public ThrowOnErrorDeserializing bool
---@field public ThrowOnErrorSerializing bool
