---@class ExchangeAlgorithmType : Enum
---@field public value__ number
---@field public None number
---@field public DiffieHellman number
---@field public RsaKeyX number
---@field public RsaSign number
