---@class DVASPECT : Enum
---@field public value__ number
---@field public DVASPECT_CONTENT number
---@field public DVASPECT_THUMBNAIL number
---@field public DVASPECT_ICON number
---@field public DVASPECT_DOCPRINT number
