---@class SoapOption : Enum
---@field public value__ number
---@field public None number
---@field public AlwaysIncludeTypes number
---@field public XsdString number
---@field public EmbedAll number
---@field public Option1 number
---@field public Option2 number
