---@class SuppressMessageAttribute : Attribute
---@field public Category string
---@field public CheckId string
---@field public Justification string
---@field public MessageId string
---@field public Scope string
---@field public Target string
