---@class CodeMemberEvent : CodeTypeMember
---@field public ImplementationTypes CodeTypeReferenceCollection
---@field public PrivateImplementationType CodeTypeReference
---@field public Type CodeTypeReference
