---@class XObjectChangeEventArgs : EventArgs
---@field public Add XObjectChangeEventArgs
---@field public Name XObjectChangeEventArgs
---@field public Remove XObjectChangeEventArgs
---@field public Value XObjectChangeEventArgs
---@field public ObjectChange number
