---@class AsnDecodeStatus : Enum
---@field public value__ number
---@field public NotDecoded number
---@field public Ok number
---@field public BadAsn number
---@field public BadTag number
---@field public BadLength number
---@field public InformationNotAvailable number
