---@class SslPolicyErrors : Enum
---@field public value__ number
---@field public None number
---@field public RemoteCertificateNotAvailable number
---@field public RemoteCertificateNameMismatch number
---@field public RemoteCertificateChainErrors number
