---@class TransferEncoding : Enum
---@field public value__ number
---@field public QuotedPrintable number
---@field public Base64 number
---@field public SevenBit number
---@field public Unknown number
