---@class Consistency : Enum
---@field public value__ number
---@field public MayCorruptAppDomain number
---@field public MayCorruptInstance number
---@field public MayCorruptProcess number
---@field public WillNotCorruptState number
