---@class ExceptionHandlingClauseOptions : Enum
---@field public value__ number
---@field public Clause number
---@field public Filter number
---@field public Finally number
---@field public Fault number
