---@class PrefixOrigin : Enum
---@field public value__ number
---@field public Other number
---@field public Manual number
---@field public WellKnown number
---@field public Dhcp number
---@field public RouterAdvertisement number
