---@class DuplicateAddressDetectionState : Enum
---@field public value__ number
---@field public Invalid number
---@field public Tentative number
---@field public Duplicate number
---@field public Deprecated number
---@field public Preferred number
