---@class SerialPinChange : Enum
---@field public value__ number
---@field public CtsChanged number
---@field public DsrChanged number
---@field public CDChanged number
---@field public Break number
---@field public Ring number
