---@class LIBFLAGS : Enum
---@field public value__ number
---@field public LIBFLAG_FRESTRICTED number
---@field public LIBFLAG_FCONTROL number
---@field public LIBFLAG_FHIDDEN number
---@field public LIBFLAG_FHASDISKIMAGE number
