---@class TrustManagerContext
---@field public IgnorePersistedDecision bool
---@field public KeepAlive bool
---@field public NoPrompt bool
---@field public Persist bool
---@field public PreviousApplicationIdentity ApplicationIdentity
---@field public UIContext number
