---@class ObjectRecordStatus : Enum
---@field public value__ number
---@field public Unregistered number
---@field public ReferenceUnsolved number
---@field public ReferenceSolvingDelayed number
---@field public ReferenceSolved number
