---@class StandardToolWindows
---@field public ObjectBrowser Guid
---@field public OutputWindow Guid
---@field public ProjectExplorer Guid
---@field public PropertyBrowser Guid
---@field public RelatedLinks Guid
---@field public ServerExplorer Guid
---@field public TaskList Guid
---@field public Toolbox Guid
