---@class EventLogEntryType : Enum
---@field public value__ number
---@field public Error number
---@field public Warning number
---@field public Information number
---@field public SuccessAudit number
---@field public FailureAudit number
