---@class SmtpSection : ConfigurationSection
---@field public DeliveryMethod number
---@field public From string
---@field public Network SmtpNetworkElement
---@field public SpecifiedPickupDirectory SmtpSpecifiedPickupDirectoryElement
