---@class CallingConvention : Enum
---@field public value__ number
---@field public Winapi number
---@field public Cdecl number
---@field public StdCall number
---@field public ThisCall number
---@field public FastCall number
