---@class Compiler : ConfigurationElement
---@field public CompilerOptions string
---@field public Extension string
---@field public Language string
---@field public Type string
---@field public WarningLevel number
---@field public ProviderOptions CompilerProviderOptionsCollection
---@field public ProviderOptionsDictionary Dictionary`2
