---@class RegistrationConnectionType : Enum
---@field public value__ number
---@field public MultipleUse number
---@field public MultiSeparate number
---@field public SingleUse number
---@field public Suspended number
---@field public Surrogate number
