---@class MonoIOStat : ValueType
---@field public Name string
---@field public Attributes number
---@field public Length number
---@field public CreationTime number
---@field public LastAccessTime number
---@field public LastWriteTime number
