---@class SymLanguageType
---@field public Basic Guid
---@field public C Guid
---@field public Cobol Guid
---@field public CPlusPlus Guid
---@field public CSharp Guid
---@field public ILAssembly Guid
---@field public Java Guid
---@field public JScript Guid
---@field public MCPlusPlus Guid
---@field public Pascal Guid
---@field public SMC Guid
