---@class XmlDateTimeSerializationMode : Enum
---@field public value__ number
---@field public Local number
---@field public Utc number
---@field public Unspecified number
---@field public RoundtripKind number
