---@class AssemblyBuilderAccess : Enum
---@field public value__ number
---@field public Run number
---@field public Save number
---@field public RunAndSave number
---@field public ReflectionOnly number
