---@class sockaddr_ll : ValueType
---@field public sll_family number
---@field public sll_protocol number
---@field public sll_ifindex number
---@field public sll_hatype number
---@field public sll_pkttype number
---@field public sll_halen number
---@field public sll_addr Byte[]
