---@class IAppDomainSetup
---@field public ApplicationBase string
---@field public ApplicationName string
---@field public CachePath string
---@field public ConfigurationFile string
---@field public DynamicBase string
---@field public LicenseFile string
---@field public PrivateBinPath string
---@field public PrivateBinPathProbe string
---@field public ShadowCopyDirectories string
---@field public ShadowCopyFiles string
