---@class ValidationType : Enum
---@field public value__ number
---@field public None number
---@field public Auto number
---@field public DTD number
---@field public XDR number
---@field public Schema number
