---@class PortableExecutableKinds : Enum
---@field public value__ number
---@field public NotAPortableExecutableImage number
---@field public ILOnly number
---@field public Required32Bit number
---@field public PE32Plus number
---@field public Unmanaged32Bit number
