---@class TYPELIBATTR : ValueType
---@field public guid Guid
---@field public lcid number
---@field public syskind number
---@field public wMajorVerNum number
---@field public wMinorVerNum number
---@field public wLibFlags number
