---@class VARKIND : Enum
---@field public value__ number
---@field public VAR_PERINSTANCE number
---@field public VAR_STATIC number
---@field public VAR_CONST number
---@field public VAR_DISPATCH number
