---@class PerformanceCounterPermissionAccess : Enum
---@field public value__ number
---@field public None number
---@field public Browse number
---@field public Read number
---@field public Write number
---@field public Instrument number
---@field public Administer number
