---@class MonoPropertyInfo : ValueType
---@field public parent Type
---@field public name string
---@field public get_method MethodInfo
---@field public set_method MethodInfo
---@field public attrs number
