---@class CodeGeneratorOptions
---@field public BlankLinesBetweenMembers bool
---@field public BracingStyle string
---@field public ElseOnClosing bool
---@field public IndentString string
---@field public Item Object
---@field public VerbatimOrder bool
