---@class HelpContextType : Enum
---@field public value__ number
---@field public Ambient number
---@field public Window number
---@field public Selection number
---@field public ToolWindowSelection number
