---@class MonoFileType : Enum
---@field public value__ number
---@field public Unknown number
---@field public Disk number
---@field public Char number
---@field public Pipe number
---@field public Remote number
