---@class PropertyInformation
---@field public Converter TypeConverter
---@field public DefaultValue Object
---@field public Description string
---@field public IsKey bool
---@field public IsLocked bool
---@field public IsModified bool
---@field public IsRequired bool
---@field public LineNumber number
---@field public Name string
---@field public Source string
---@field public Type Type
---@field public Validator ConfigurationValidatorBase
---@field public Value Object
---@field public ValueOrigin number
