---@class StringComparison : Enum
---@field public value__ number
---@field public CurrentCulture number
---@field public CurrentCultureIgnoreCase number
---@field public InvariantCulture number
---@field public InvariantCultureIgnoreCase number
---@field public Ordinal number
---@field public OrdinalIgnoreCase number
