---@class HookType : Enum
---@field public value__ number
---@field public attributes number
---@field public elements number
---@field public unknownAttribute number
---@field public unknownElement number
---@field public member number
---@field public type number
