---@class TraceEventCache
---@field public Callstack string
---@field public DateTime DateTime
---@field public LogicalOperationStack Stack
---@field public ProcessId number
---@field public ThreadId string
---@field public Timestamp number
