---@class ControlCharacters
---@field public Intr number
---@field public Quit number
---@field public Erase number
---@field public Kill number
---@field public EOF number
---@field public Time number
---@field public Min number
---@field public SWTC number
---@field public Start number
---@field public Stop number
---@field public Susp number
---@field public EOL number
---@field public Reprint number
---@field public Discard number
---@field public WErase number
---@field public LNext number
---@field public EOL2 number
