---@class EventSourceCreationData
---@field public CategoryCount number
---@field public CategoryResourceFile string
---@field public LogName string
---@field public MachineName string
---@field public MessageResourceFile string
---@field public ParameterResourceFile string
---@field public Source string
