---@class INVOKEKIND : Enum
---@field public value__ number
---@field public INVOKE_FUNC number
---@field public INVOKE_PROPERTYGET number
---@field public INVOKE_PROPERTYPUT number
---@field public INVOKE_PROPERTYPUTREF number
