---@class SslProtocols : Enum
---@field public value__ number
---@field public None number
---@field public Ssl2 number
---@field public Ssl3 number
---@field public Tls number
---@field public Default number
