---@class ConfigurationSaveEventArgs : EventArgs
---@field public StreamPath string
---@field public Start bool
---@field public Context Object
---@field public Failed bool
---@field public Exception Exception
