---@class ImporterEventKind : Enum
---@field public value__ number
---@field public NOTIF_TYPECONVERTED number
---@field public NOTIF_CONVERTWARNING number
---@field public ERROR_REFTOINVALIDTYPELIB number
