---@class IMPLTYPEFLAGS : Enum
---@field public value__ number
---@field public IMPLTYPEFLAG_FDEFAULT number
---@field public IMPLTYPEFLAG_FSOURCE number
---@field public IMPLTYPEFLAG_FRESTRICTED number
---@field public IMPLTYPEFLAG_FDEFAULTVTABLE number
