---@class SocketType : Enum
---@field public value__ number
---@field public Stream number
---@field public Dgram number
---@field public Raw number
---@field public Rdm number
---@field public Seqpacket number
---@field public Unknown number
