---@class AccessControlSections : Enum
---@field public value__ number
---@field public None number
---@field public Audit number
---@field public Access number
---@field public Owner number
---@field public Group number
---@field public All number
