---@class SerialSignal : Enum
---@field public value__ number
---@field public None number
---@field public Cd number
---@field public Cts number
---@field public Dsr number
---@field public Dtr number
---@field public Rts number
