---@class DebuggerVisualizerAttribute : Attribute
---@field public Description string
---@field public Target Type
---@field public TargetTypeName string
---@field public VisualizerObjectSourceTypeName string
---@field public VisualizerTypeName string
