---@class ifaddrs : ValueType
---@field public ifa_next IntPtr
---@field public ifa_name string
---@field public ifa_flags number
---@field public ifa_addr IntPtr
---@field public ifa_netmask IntPtr
---@field public ifa_ifu ifa_ifu
---@field public ifa_data IntPtr
