---@class CodeTryCatchFinallyStatement : CodeStatement
---@field public FinallyStatements CodeStatementCollection
---@field public TryStatements CodeStatementCollection
---@field public CatchClauses CodeCatchClauseCollection
