---@class ProtectedConfiguration
---@field public DataProtectionProviderName string
---@field public ProtectedDataSectionName string
---@field public RsaProviderName string
---@field public DefaultProvider string
---@field public Providers ProtectedConfigurationProviderCollection
