---@class IDLFLAG : Enum
---@field public value__ number
---@field public IDLFLAG_NONE number
---@field public IDLFLAG_FIN number
---@field public IDLFLAG_FOUT number
---@field public IDLFLAG_FLCID number
---@field public IDLFLAG_FRETVAL number
