---@class LongValidatorAttribute : ConfigurationValidatorAttribute
---@field public ExcludeRange bool
---@field public MaxValue number
---@field public MinValue number
---@field public ValidatorInstance ConfigurationValidatorBase
