---@class ApplicationSecurityInfo
---@field public ApplicationEvidence Evidence
---@field public ApplicationId ApplicationId
---@field public DefaultRequestSet PermissionSet
---@field public DeploymentId ApplicationId
