---@class ConfigurationProperty
---@field public Converter TypeConverter
---@field public DefaultValue Object
---@field public IsKey bool
---@field public IsRequired bool
---@field public IsDefaultCollection bool
---@field public Name string
---@field public Description string
---@field public Type Type
---@field public Validator ConfigurationValidatorBase
