---@class Parity : Enum
---@field public value__ number
---@field public None number
---@field public Odd number
---@field public Even number
---@field public Mark number
---@field public Space number
