---@class LoadOptions : Enum
---@field public value__ number
---@field public None number
---@field public PreserveWhitespace number
---@field public SetBaseUri number
---@field public SetLineInfo number
