---@class CipherMode : Enum
---@field public value__ number
---@field public CBC number
---@field public ECB number
---@field public OFB number
---@field public CFB number
---@field public CTS number
