---@class ConfigurationAllowExeDefinition : Enum
---@field public value__ number
---@field public MachineOnly number
---@field public MachineToApplication number
---@field public MachineToLocalUser number
---@field public MachineToRoamingUser number
