---@class ConfigurationPropertyOptions : Enum
---@field public value__ number
---@field public None number
---@field public IsDefaultCollection number
---@field public IsRequired number
---@field public IsKey number
