---@class WatcherChangeTypes : Enum
---@field public value__ number
---@field public All number
---@field public Changed number
---@field public Created number
---@field public Deleted number
---@field public Renamed number
