---@class ConfigurationElementCollectionType : Enum
---@field public value__ number
---@field public BasicMap number
---@field public AddRemoveClearMap number
---@field public BasicMapAlternate number
---@field public AddRemoveClearMapAlternate number
