---@class OpenFlags : Enum
---@field public value__ number
---@field public ReadOnly number
---@field public ReadWrite number
---@field public MaxAllowed number
---@field public OpenExistingOnly number
---@field public IncludeArchived number
