---@class FAMData
---@field public FSW FileSystemWatcher
---@field public Directory string
---@field public FileMask string
---@field public IncludeSubdirs bool
---@field public Enabled bool
---@field public Request FAMRequest
---@field public SubDirs Hashtable
