---@class StringValidatorAttribute : ConfigurationValidatorAttribute
---@field public InvalidCharacters string
---@field public MaxLength number
---@field public MinLength number
---@field public ValidatorInstance ConfigurationValidatorBase
