---@class UploadProgressChangedEventArgs : ProgressChangedEventArgs
---@field public BytesReceived number
---@field public TotalBytesToReceive number
---@field public BytesSent number
---@field public TotalBytesToSend number
