---@class SettingsSerializeAs : Enum
---@field public value__ number
---@field public String number
---@field public Xml number
---@field public Binary number
---@field public ProviderSpecific number
