---@class TransmitFileOptions : Enum
---@field public value__ number
---@field public UseDefaultWorkerThread number
---@field public Disconnect number
---@field public ReuseSocket number
---@field public WriteBehind number
---@field public UseSystemThread number
---@field public UseKernelApc number
