---@class ReadState : Enum
---@field public value__ number
---@field public Initial number
---@field public Interactive number
---@field public Error number
---@field public EndOfFile number
---@field public Closed number
