---@class BinaryExpression : Expression
---@field public Left Expression
---@field public Right Expression
---@field public Method MethodInfo
---@field public IsLifted bool
---@field public IsLiftedToNull bool
---@field public Conversion LambdaExpression
