---@class XmlNodeChangedEventArgs : EventArgs
---@field public Action number
---@field public Node XmlNode
---@field public OldParent XmlNode
---@field public NewParent XmlNode
---@field public OldValue string
---@field public NewValue string
