---@class XmlElementAttribute : Attribute
---@field public DataType string
---@field public ElementName string
---@field public Form number
---@field public Namespace string
---@field public IsNullable bool
---@field public Order number
---@field public Type Type
