---@class PInfo : Enum
---@field public value__ number
---@field public Attributes number
---@field public GetMethod number
---@field public SetMethod number
---@field public ReflectedType number
---@field public DeclaringType number
---@field public Name number
