---@class MonoResource : ValueType
---@field public data Byte[]
---@field public name string
---@field public filename string
---@field public attrs number
---@field public offset number
---@field public stream Stream
