---@class XmlRootAttribute : Attribute
---@field public DataType string
---@field public ElementName string
---@field public IsNullable bool
---@field public IsNullableSpecified bool
---@field public Namespace string
