---@class AceQualifier : Enum
---@field public value__ number
---@field public AccessAllowed number
---@field public AccessDenied number
---@field public SystemAudit number
---@field public SystemAlarm number
