---@class DataObjectMethodType : Enum
---@field public value__ number
---@field public Fill number
---@field public Select number
---@field public Update number
---@field public Insert number
---@field public Delete number
