---@class SmtpNetworkElement : ConfigurationElement
---@field public DefaultCredentials bool
---@field public Host string
---@field public Password string
---@field public Port number
---@field public UserName string
