---@class Handshake : Enum
---@field public value__ number
---@field public None number
---@field public XOnXOff number
---@field public RequestToSend number
---@field public RequestToSendXOnXOff number
