---@class XmlAttributes
---@field public XmlAnyAttribute XmlAnyAttributeAttribute
---@field public XmlAnyElements XmlAnyElementAttributes
---@field public XmlArray XmlArrayAttribute
---@field public XmlArrayItems XmlArrayItemAttributes
---@field public XmlAttribute XmlAttributeAttribute
---@field public XmlChoiceIdentifier XmlChoiceIdentifierAttribute
---@field public XmlDefaultValue Object
---@field public XmlElements XmlElementAttributes
---@field public XmlEnum XmlEnumAttribute
---@field public XmlIgnore bool
---@field public Xmlns bool
---@field public XmlRoot XmlRootAttribute
---@field public XmlText XmlTextAttribute
---@field public XmlType XmlTypeAttribute
