---@class CodeTypeReference : CodeObject
---@field public ArrayElementType CodeTypeReference
---@field public ArrayRank number
---@field public BaseType string
---@field public Options number
---@field public TypeArguments CodeTypeReferenceCollection
