---@class LeaseState : Enum
---@field public value__ number
---@field public Null number
---@field public Initial number
---@field public Active number
---@field public Renewing number
---@field public Expired number
