---@class ThreadPriority : Enum
---@field public value__ number
---@field public Lowest number
---@field public BelowNormal number
---@field public Normal number
---@field public AboveNormal number
---@field public Highest number
