---@class IConstructionCallMessage
---@field public ActivationType Type
---@field public ActivationTypeName string
---@field public Activator IActivator
---@field public CallSiteActivationAttributes Object[]
---@field public ContextProperties IList
