---@class XmlAttributeAttribute : Attribute
---@field public AttributeName string
---@field public DataType string
---@field public Form number
---@field public Namespace string
---@field public Type Type
