---@class Win32_MIB_UDPSTATS : ValueType
---@field public InDatagrams number
---@field public NoPorts number
---@field public InErrors number
---@field public OutDatagrams number
---@field public NumAddrs number
