---@class EventLogPermissionAccess : Enum
---@field public value__ number
---@field public None number
---@field public Browse number
---@field public Instrument number
---@field public Audit number
---@field public Write number
---@field public Administer number
