---@class XmlSchemaAttributeGroup : XmlSchemaAnnotated
---@field public Name string
---@field public Attributes XmlSchemaObjectCollection
---@field public AnyAttribute XmlSchemaAnyAttribute
---@field public RedefinedAttributeGroup XmlSchemaAttributeGroup
---@field public QualifiedName XmlQualifiedName
