---@class XmlSchemaObject
---@field public LineNumber number
---@field public LinePosition number
---@field public SourceUri string
---@field public Parent XmlSchemaObject
---@field public Namespaces XmlSerializerNamespaces
