---@class IPv4InterfaceProperties
---@field public Index number
---@field public IsAutomaticPrivateAddressingActive bool
---@field public IsAutomaticPrivateAddressingEnabled bool
---@field public IsDhcpEnabled bool
---@field public IsForwardingEnabled bool
---@field public Mtu number
---@field public UsesWins bool
