---@class AspNetHostingPermissionLevel : Enum
---@field public value__ number
---@field public None number
---@field public Minimal number
---@field public Low number
---@field public Medium number
---@field public High number
---@field public Unrestricted number
