---@class ISymbolVariable
---@field public AddressField1 number
---@field public AddressField2 number
---@field public AddressField3 number
---@field public AddressKind number
---@field public Attributes Object
---@field public EndOffset number
---@field public Name string
---@field public StartOffset number
---@public
---@return Byte[]
function ISymbolVariable:GetSignature() end
