---@class XmlArrayAttribute : Attribute
---@field public ElementName string
---@field public Form number
---@field public IsNullable bool
---@field public Namespace string
---@field public Order number
