---@class ExceptionHandlingClause
---@field public CatchType Type
---@field public FilterOffset number
---@field public Flags number
---@field public HandlerLength number
---@field public HandlerOffset number
---@field public TryLength number
---@field public TryOffset number
---@public
---@return string
function ExceptionHandlingClause:ToString() end
