---@class NetBiosNodeType : Enum
---@field public value__ number
---@field public Unknown number
---@field public Broadcast number
---@field public Peer2Peer number
---@field public Mixed number
---@field public Hybrid number
