---@class TokenImpersonationLevel : Enum
---@field public value__ number
---@field public Anonymous number
---@field public Delegation number
---@field public Identification number
---@field public Impersonation number
---@field public None number
