---@class TransportType : Enum
---@field public value__ number
---@field public Udp number
---@field public Connectionless number
---@field public Tcp number
---@field public ConnectionOriented number
---@field public All number
