---@class ProxyElement : ConfigurationElement
---@field public AutoDetect number
---@field public BypassOnLocal number
---@field public ProxyAddress Uri
---@field public ScriptLocation Uri
---@field public UseSystemDefault number
