---@class XmlSchemaComplexContentRestriction : XmlSchemaContent
---@field public BaseTypeName XmlQualifiedName
---@field public Particle XmlSchemaParticle
---@field public Attributes XmlSchemaObjectCollection
---@field public AnyAttribute XmlSchemaAnyAttribute
