---@class CodeCompileUnit : CodeObject
---@field public AssemblyCustomAttributes CodeAttributeDeclarationCollection
---@field public Namespaces CodeNamespaceCollection
---@field public ReferencedAssemblies StringCollection
---@field public StartDirectives CodeDirectiveCollection
---@field public EndDirectives CodeDirectiveCollection
