---@class GenerationResult
---@field public Mapping XmlMapping
---@field public ReaderClassName string
---@field public ReadMethodName string
---@field public WriterClassName string
---@field public WriteMethodName string
---@field public Namespace string
---@field public SerializerClassName string
---@field public BaseSerializerClassName string
---@field public ImplementationClassName string
