---@class CodeTypeMember : CodeObject
---@field public Attributes number
---@field public Comments CodeCommentStatementCollection
---@field public CustomAttributes CodeAttributeDeclarationCollection
---@field public LinePragma CodeLinePragma
---@field public Name string
---@field public EndDirectives CodeDirectiveCollection
---@field public StartDirectives CodeDirectiveCollection
