---@class XmlArrayItemAttribute : Attribute
---@field public DataType string
---@field public ElementName string
---@field public Form number
---@field public Namespace string
---@field public IsNullable bool
---@field public Type Type
---@field public NestingLevel number
