---@class XmlSchemaValidationFlags : Enum
---@field public value__ number
---@field public None number
---@field public ProcessInlineSchema number
---@field public ProcessSchemaLocation number
---@field public ReportValidationWarnings number
---@field public ProcessIdentityConstraints number
---@field public AllowXmlAttributes number
