---@class XmlSchemaIdentityConstraint : XmlSchemaAnnotated
---@field public Name string
---@field public Selector XmlSchemaXPath
---@field public Fields XmlSchemaObjectCollection
---@field public QualifiedName XmlQualifiedName
