---@class DateTimeFormatFlags : Enum
---@field public value__ number
---@field public Unused number
---@field public But number
---@field public Serialized number
---@field public By number
---@field public Microsoft number
