---@class OpFlags : Enum
---@field public value__ number
---@field public None number
---@field public Negate number
---@field public IgnoreCase number
---@field public RightToLeft number
---@field public Lazy number
