---@class CallingConventions : Enum
---@field public value__ number
---@field public Standard number
---@field public VarArgs number
---@field public Any number
---@field public HasThis number
---@field public ExplicitThis number
