---@class FUNCKIND : Enum
---@field public value__ number
---@field public FUNC_VIRTUAL number
---@field public FUNC_PUREVIRTUAL number
---@field public FUNC_NONVIRTUAL number
---@field public FUNC_STATIC number
---@field public FUNC_DISPATCH number
