---@class ICONDIRENTRY
---@field public bWidth number
---@field public bHeight number
---@field public bColorCount number
---@field public bReserved number
---@field public wPlanes number
---@field public wBitCount number
---@field public dwBytesInRes number
---@field public dwImageOffset number
---@field public image Byte[]
---@public
---@return string
function ICONDIRENTRY:ToString() end
