---@class ISoapMessage
---@field public Headers Header[]
---@field public MethodName string
---@field public ParamNames String[]
---@field public ParamTypes Type[]
---@field public ParamValues Object[]
---@field public XmlNameSpace string
