---@class CodeIterationStatement : CodeStatement
---@field public IncrementStatement CodeStatement
---@field public InitStatement CodeStatement
---@field public Statements CodeStatementCollection
---@field public TestExpression CodeExpression
