---@class X509KeyStorageFlags : Enum
---@field public value__ number
---@field public DefaultKeySet number
---@field public UserKeySet number
---@field public MachineKeySet number
---@field public Exportable number
---@field public UserProtected number
---@field public PersistKeySet number
