---@class UriHostNameType : Enum
---@field public value__ number
---@field public Unknown number
---@field public Basic number
---@field public Dns number
---@field public IPv4 number
---@field public IPv6 number
