---@class CompilerResults
---@field public CompiledAssembly Assembly
---@field public Errors CompilerErrorCollection
---@field public Evidence Evidence
---@field public NativeCompilerReturnValue number
---@field public Output StringCollection
---@field public PathToAssembly string
---@field public TempFiles TempFileCollection
