---@class XmlSchemaRedefine : XmlSchemaExternal
---@field public Items XmlSchemaObjectCollection
---@field public AttributeGroups XmlSchemaObjectTable
---@field public SchemaTypes XmlSchemaObjectTable
---@field public Groups XmlSchemaObjectTable
