---@class ActivatorLevel : Enum
---@field public value__ number
---@field public Construction number
---@field public Context number
---@field public AppDomain number
---@field public Process number
---@field public Machine number
