---@class XmlSchemaSimpleTypeList : XmlSchemaSimpleTypeContent
---@field public ItemTypeName XmlQualifiedName
---@field public ItemType XmlSchemaSimpleType
---@field public BaseItemType XmlSchemaSimpleType
