---@class IConfigurationManagerInternal
---@field public ApplicationConfigUri string
---@field public ExeLocalConfigDirectory string
---@field public ExeLocalConfigPath string
---@field public ExeProductName string
---@field public ExeProductVersion string
---@field public ExeRoamingConfigDirectory string
---@field public ExeRoamingConfigPath string
---@field public MachineConfigPath string
---@field public SetConfigurationSystemInProgress bool
---@field public SupportsUserConfig bool
---@field public UserConfigFilename string
