---@class ServicePointManagerElement : ConfigurationElement
---@field public CheckCertificateName bool
---@field public CheckCertificateRevocationList bool
---@field public DnsRefreshTimeout number
---@field public EnableDnsRoundRobin bool
---@field public Expect100Continue bool
---@field public UseNagleAlgorithm bool
