---@class DefaultProxySection : ConfigurationSection
---@field public BypassList BypassElementCollection
---@field public Enabled bool
---@field public Module ModuleElement
---@field public Proxy ProxyElement
---@field public UseDefaultCredentials bool
