---@class X509NameType : Enum
---@field public value__ number
---@field public SimpleName number
---@field public EmailName number
---@field public UpnName number
---@field public DnsName number
---@field public DnsFromAlternativeName number
---@field public UrlName number
