---@class SettingsPropertyValue
---@field public Deserialized bool
---@field public IsDirty bool
---@field public Name string
---@field public Property SettingsProperty
---@field public PropertyValue Object
---@field public SerializedValue Object
---@field public UsingDefaultValue bool
