---@class SoapMethodAttribute : SoapAttribute
---@field public ResponseXmlElementName string
---@field public ResponseXmlNamespace string
---@field public ReturnXmlElementName string
---@field public SoapAction string
---@field public UseAttribute bool
---@field public XmlNamespace string
