---@class SocketInformationOptions : Enum
---@field public value__ number
---@field public NonBlocking number
---@field public Connected number
---@field public Listening number
---@field public UseOnlyOverlappedIO number
