---@class SoapAttributes
---@field public SoapAttribute SoapAttributeAttribute
---@field public SoapDefaultValue Object
---@field public SoapElement SoapElementAttribute
---@field public SoapEnum SoapEnumAttribute
---@field public SoapIgnore bool
---@field public SoapType SoapTypeAttribute
