---@class UnixIPv4InterfaceProperties : IPv4InterfaceProperties
---@field public Index number
---@field public IsAutomaticPrivateAddressingActive bool
---@field public IsAutomaticPrivateAddressingEnabled bool
---@field public IsDhcpEnabled bool
---@field public UsesWins bool
