---@class XmlDeserializationEvents : ValueType
---@field public OnUnknownAttribute XmlAttributeEventHandler
---@field public OnUnknownElement XmlElementEventHandler
---@field public OnUnknownNode XmlNodeEventHandler
---@field public OnUnreferencedObject UnreferencedObjectEventHandler
