---@class Mark : ValueType
---@field public Start number
---@field public End number
---@field public Previous number
---@field public IsDefined bool
---@field public Index number
---@field public Length number
