---@class ListChangedEventArgs : EventArgs
---@field public ListChangedType number
---@field public OldIndex number
---@field public NewIndex number
---@field public PropertyDescriptor PropertyDescriptor
