---@class CodeParameterDeclarationExpression : CodeExpression
---@field public CustomAttributes CodeAttributeDeclarationCollection
---@field public Direction number
---@field public Name string
---@field public Type CodeTypeReference
