---@class GCNotificationStatus : Enum
---@field public value__ number
---@field public Succeeded number
---@field public Failed number
---@field public Canceled number
---@field public Timeout number
---@field public NotApplicable number
