---@class GregorianCalendarTypes : Enum
---@field public value__ number
---@field public Localized number
---@field public USEnglish number
---@field public MiddleEastFrench number
---@field public Arabic number
---@field public TransliteratedEnglish number
---@field public TransliteratedFrench number
