---@class SystemSounds
---@field public Asterisk SystemSound
---@field public Beep SystemSound
---@field public Exclamation SystemSound
---@field public Hand SystemSound
---@field public Question SystemSound
