---@class CalendarAlgorithmType : Enum
---@field public value__ number
---@field public Unknown number
---@field public SolarCalendar number
---@field public LunarCalendar number
---@field public LunisolarCalendar number
