---@class ElementInformation
---@field public Errors ICollection
---@field public IsCollection bool
---@field public IsLocked bool
---@field public IsPresent bool
---@field public LineNumber number
---@field public Source string
---@field public Type Type
---@field public Validator ConfigurationValidatorBase
---@field public Properties PropertyInformationCollection
