---@class ProcessorArchitecture : Enum
---@field public value__ number
---@field public None number
---@field public MSIL number
---@field public X86 number
---@field public IA64 number
---@field public Amd64 number
