---@class sockaddr_in6 : ValueType
---@field public sin6_len number
---@field public sin6_family number
---@field public sin6_port number
---@field public sin6_flowinfo number
---@field public sin6_addr in6_addr
---@field public sin6_scope_id number
