---@class CodeTypeParameter : CodeObject
---@field public Constraints CodeTypeReferenceCollection
---@field public CustomAttributes CodeAttributeDeclarationCollection
---@field public HasConstructorConstraint bool
---@field public Name string
