---@class UnmanagedFunctionPointerAttribute : Attribute
---@field public CharSet number
---@field public SetLastError bool
---@field public BestFitMapping bool
---@field public ThrowOnUnmappableChar bool
---@field public CallingConvention number
