---@class IXmlSchemaInfo
---@field public IsDefault bool
---@field public IsNil bool
---@field public MemberType XmlSchemaSimpleType
---@field public SchemaAttribute XmlSchemaAttribute
---@field public SchemaElement XmlSchemaElement
---@field public SchemaType XmlSchemaType
---@field public Validity number
