---@class DebuggerDisplayAttribute : Attribute
---@field public Value string
---@field public Target Type
---@field public TargetTypeName string
---@field public Type string
---@field public Name string
