---@class RequestCachingSection : ConfigurationSection
---@field public DefaultFtpCachePolicy FtpCachePolicyElement
---@field public DefaultHttpCachePolicy HttpCachePolicyElement
---@field public DefaultPolicyLevel number
---@field public DisableAllCaching bool
---@field public IsPrivateCache bool
---@field public UnspecifiedMaximumAge TimeSpan
