---@class AccessControlModification : Enum
---@field public value__ number
---@field public Add number
---@field public Set number
---@field public Reset number
---@field public Remove number
---@field public RemoveAll number
---@field public RemoveSpecific number
