---@class XmlElementEventArgs : EventArgs
---@field public Element XmlElement
---@field public LineNumber number
---@field public LinePosition number
---@field public ObjectBeingDeserialized Object
---@field public ExpectedElements string
