---@class XmlSchemaSimpleTypeUnion : XmlSchemaSimpleTypeContent
---@field public BaseTypes XmlSchemaObjectCollection
---@field public MemberTypes XmlQualifiedName[]
---@field public BaseMemberTypes XmlSchemaSimpleType[]
