---@class MulticastIPAddressInformation : IPAddressInformation
---@field public AddressPreferredLifetime number
---@field public AddressValidLifetime number
---@field public DhcpLeaseLifetime number
---@field public DuplicateAddressDetectionState number
---@field public PrefixOrigin number
---@field public SuffixOrigin number
