---@class X509IncludeOption : Enum
---@field public value__ number
---@field public None number
---@field public ExcludeRoot number
---@field public EndCertOnly number
---@field public WholeChain number
