---@class XmlSchemaSimpleTypeRestriction : XmlSchemaSimpleTypeContent
---@field public BaseTypeName XmlQualifiedName
---@field public BaseType XmlSchemaSimpleType
---@field public Facets XmlSchemaObjectCollection
