---@class InputRecord : ValueType
---@field public EventType number
---@field public KeyDown bool
---@field public RepeatCount number
---@field public VirtualKeyCode number
---@field public VirtualScanCode number
---@field public Character Char
---@field public ControlKeyState number
