---@class MibUdpStatistics : UdpStatistics
---@field public DatagramsReceived number
---@field public DatagramsSent number
---@field public IncomingDatagramsDiscarded number
---@field public IncomingDatagramsWithErrors number
---@field public UdpListeners number
