---@class CodeArrayCreateExpression : CodeExpression
---@field public CreateType CodeTypeReference
---@field public Initializers CodeExpressionCollection
---@field public SizeExpression CodeExpression
---@field public Size number
