---@class TraceImplSettings
---@field public Key string
---@field public AutoFlush bool
---@field public IndentLevel number
---@field public IndentSize number
---@field public Listeners TraceListenerCollection
