---@class VARDESC : ValueType
---@field public memid number
---@field public lpstrSchema string
---@field public desc DESCUNION
---@field public elemdescVar ELEMDESC
---@field public wVarFlags number
---@field public varkind number
