---@class SettingsSection : ConfigurationSection
---@field public HttpWebRequest HttpWebRequestElement
---@field public Ipv6 Ipv6Element
---@field public PerformanceCounters PerformanceCountersElement
---@field public ServicePointManager ServicePointManagerElement
---@field public Socket SocketElement
---@field public WebProxyScript WebProxyScriptElement
