---@class ConfigurationPropertyAttribute : Attribute
---@field public IsKey bool
---@field public IsDefaultCollection bool
---@field public DefaultValue Object
---@field public Options number
---@field public Name string
---@field public IsRequired bool
