---@class UriData
---@field public AbsolutePath string
---@field public AbsoluteUri string
---@field public AbsoluteUri_SafeUnescaped string
---@field public Authority string
---@field public Fragment string
---@field public Host string
---@field public PathAndQuery string
---@field public StrongPort string
---@field public Query string
---@field public UserInfo string
