---@class Win32_IP_PER_ADAPTER_INFO
---@field public AutoconfigEnabled number
---@field public AutoconfigActive number
---@field public CurrentDnsServer IntPtr
---@field public DnsServerList Win32_IP_ADDR_STRING
