---@class MacOsArpHardware : Enum
---@field public value__ number
---@field public ETHER number
---@field public ATM number
---@field public SLIP number
---@field public PPP number
---@field public LOOPBACK number
---@field public FDDI number
