---@class CspKeyContainerInfo
---@field public Accessible bool
---@field public CryptoKeySecurity CryptoKeySecurity
---@field public Exportable bool
---@field public HardwareDevice bool
---@field public KeyContainerName string
---@field public KeyNumber number
---@field public MachineKeyStore bool
---@field public Protected bool
---@field public ProviderName string
---@field public ProviderType number
---@field public RandomlyGenerated bool
---@field public Removable bool
---@field public UniqueKeyContainerName string
