---@class PolicyStatementAttribute : Enum
---@field public value__ number
---@field public Nothing number
---@field public Exclusive number
---@field public LevelFinal number
---@field public All number
