---@class HttpCachePolicyElement : ConfigurationElement
---@field public MaximumAge TimeSpan
---@field public MaximumStale TimeSpan
---@field public MinimumFresh TimeSpan
---@field public PolicyLevel number
