---@class CspParameters
---@field public KeyContainerName string
---@field public KeyNumber number
---@field public ProviderName string
---@field public ProviderType number
---@field public Flags number
---@field public CryptoKeySecurity CryptoKeySecurity
---@field public KeyPassword SecureString
---@field public ParentWindowHandle IntPtr
