---@class FileMode : Enum
---@field public value__ number
---@field public CreateNew number
---@field public Create number
---@field public Open number
---@field public OpenOrCreate number
---@field public Truncate number
---@field public Append number
