---@class WebAsyncResult
---@field public EndCalled bool
---@field public AsyncWriteAll bool
---@field public AsyncState Object
---@field public AsyncWaitHandle WaitHandle
---@field public CompletedSynchronously bool
---@field public IsCompleted bool
