---@class XmlSchemaSimpleContentRestriction : XmlSchemaContent
---@field public BaseTypeName XmlQualifiedName
---@field public BaseType XmlSchemaSimpleType
---@field public Facets XmlSchemaObjectCollection
---@field public Attributes XmlSchemaObjectCollection
---@field public AnyAttribute XmlSchemaAnyAttribute
