---@class ReflectionPermissionFlag : Enum
---@field public value__ number
---@field public NoFlags number
---@field public TypeInformation number
---@field public MemberAccess number
---@field public ReflectionEmit number
---@field public AllFlags number
---@field public RestrictedMemberAccess number
