---@class ProcessPriorityClass : Enum
---@field public value__ number
---@field public AboveNormal number
---@field public BelowNormal number
---@field public High number
---@field public Idle number
---@field public Normal number
---@field public RealTime number
