---@class XmlReflectionMember
---@field public IsReturnValue bool
---@field public MemberName string
---@field public MemberType Type
---@field public OverrideIsNullable bool
---@field public SoapAttributes SoapAttributes
---@field public XmlAttributes XmlAttributes
