---@class HttpCacheAgeControl : Enum
---@field public value__ number
---@field public None number
---@field public MinFresh number
---@field public MaxAge number
---@field public MaxAgeAndMinFresh number
---@field public MaxStale number
---@field public MaxAgeAndMaxStale number
