---@class AuthenticatedStream : Stream
---@field public IsAuthenticated bool
---@field public IsEncrypted bool
---@field public IsMutuallyAuthenticated bool
---@field public IsServer bool
---@field public IsSigned bool
---@field public LeaveInnerStreamOpen bool
