---@class DefaultWatcherData
---@field public FSW FileSystemWatcher
---@field public Directory string
---@field public FileMask string
---@field public IncludeSubdirs bool
---@field public Enabled bool
---@field public NoWildcards bool
---@field public DisabledTime DateTime
---@field public Files Hashtable
