---@class SecurityZone : Enum
---@field public value__ number
---@field public MyComputer number
---@field public Intranet number
---@field public Trusted number
---@field public Internet number
---@field public Untrusted number
---@field public NoZone number
