---@class CodeGenerationOptions : Enum
---@field public value__ number
---@field public None number
---@field public GenerateProperties number
---@field public GenerateNewAsync number
---@field public GenerateOldAsync number
---@field public GenerateOrder number
---@field public EnableDataBinding number
