---@class PaddingMode : Enum
---@field public value__ number
---@field public None number
---@field public PKCS7 number
---@field public Zeros number
---@field public ANSIX923 number
---@field public ISO10126 number
