---@class XmlTypeMapMemberAttribute : XmlTypeMapMember
---@field public AttributeName string
---@field public Namespace string
---@field public DataTypeNamespace string
---@field public Form number
---@field public MappedType XmlTypeMapping
