---@class TraceLevel : Enum
---@field public value__ number
---@field public Off number
---@field public Error number
---@field public Warning number
---@field public Info number
---@field public Verbose number
