---@class FileAction : Enum
---@field public value__ number
---@field public Added number
---@field public Removed number
---@field public Modified number
---@field public RenamedOldName number
---@field public RenamedNewName number
