---@class SuffixOrigin : Enum
---@field public value__ number
---@field public Other number
---@field public Manual number
---@field public WellKnown number
---@field public OriginDhcp number
---@field public LinkLayerAddress number
---@field public Random number
