---@class TypeLibExporterFlags : Enum
---@field public value__ number
---@field public OnlyReferenceRegistered number
---@field public None number
---@field public CallerResolvedReferences number
---@field public OldNames number
---@field public ExportAs32Bit number
---@field public ExportAs64Bit number
