---@class ConfigurationAllowDefinition : Enum
---@field public value__ number
---@field public MachineOnly number
---@field public MachineToWebRoot number
---@field public MachineToApplication number
---@field public Everywhere number
