---@class Authorization
---@field public Message string
---@field public Complete bool
---@field public ConnectionGroupId string
---@field public ProtectionRealm String[]
---@field public MutuallyAuthenticated bool
