---@class LoaderOptimization : Enum
---@field public value__ number
---@field public NotSpecified number
---@field public SingleDomain number
---@field public MultiDomain number
---@field public MultiDomainHost number
---@field public DomainMask number
---@field public DisallowBindings number
