---@class TextureMappingOptions : Enum
---@field public value__ number
---@field public Character number
---@field public Line number
---@field public Paragraph number
---@field public MatchAspect number
