---@class XML_TagAttribute : ValueType
---@field public nameHashCode number
---@field public valueType number
---@field public valueStartIndex number
---@field public valueLength number
---@field public valueHashCode number
