---@class _HorizontalAlignmentOptions : Enum
---@field public value__ number
---@field public Left number
---@field public Center number
---@field public Right number
---@field public Justified number
---@field public Flush number
---@field public Geometry number
