---@class KerningPair
---@field public xOffset number
---@field public firstGlyph number
---@field public firstGlyphAdjustments GlyphValueRecord
---@field public secondGlyph number
---@field public secondGlyphAdjustments GlyphValueRecord
