---@class FaceStyles : Enum
---@field public value__ number
---@field public Normal number
---@field public Bold number
---@field public Italic number
---@field public Bold_Italic number
---@field public Outline number
---@field public Bold_Sim number
