---@class _VerticalAlignmentOptions : Enum
---@field public value__ number
---@field public Top number
---@field public Middle number
---@field public Bottom number
---@field public Baseline number
---@field public Geometry number
---@field public Capline number
