---@class TMP_PageInfo : ValueType
---@field public firstCharacterIndex number
---@field public lastCharacterIndex number
---@field public ascender number
---@field public baseLine number
---@field public descender number
