---@class TMP_UIStyleManager
---@field public TMP_GUISkin GUISkin
---@field public Label GUIStyle
---@field public Group_Label GUIStyle
---@field public Group_Label_Left GUIStyle
---@field public TextAreaBoxEditor GUIStyle
---@field public TextAreaBoxWindow GUIStyle
---@field public TextureAreaBox GUIStyle
---@field public Section_Label GUIStyle
---@field public SquareAreaBox85G GUIStyle
---@field public alignLeft Texture2D
---@field public alignCenter Texture2D
---@field public alignRight Texture2D
---@field public alignJustified Texture2D
---@field public alignFlush Texture2D
---@field public alignGeoCenter Texture2D
---@field public alignTop Texture2D
---@field public alignMiddle Texture2D
---@field public alignBottom Texture2D
---@field public alignBaseline Texture2D
---@field public alignMidline Texture2D
---@field public alignCapline Texture2D
---@field public selectionBox Texture2D
---@field public alignContent_A GUIContent[]
---@field public alignContent_B GUIContent[]
---@public
---@return void
function TMP_UIStyleManager.GetUIStyles() end
