---@class TMP_Math
---@field public FLOAT_MAX number
---@field public FLOAT_MIN number
---@field public INT_MAX number
---@field public INT_MIN number
---@field public FLOAT_UNSET number
---@field public INT_UNSET number
---@field public MAX_16BIT Vector2
---@field public MIN_16BIT Vector2
---@public
---@param a number
---@param b number
---@return bool
function TMP_Math.Approximately(a, b) end
