---@class RenderModes : Enum
---@field public value__ number
---@field public HintedSmooth number
---@field public Smooth number
---@field public RasterHinted number
---@field public Raster number
---@field public DistanceField16 number
---@field public DistanceField32 number
