---@class TreeAttribute : Attribute
---@field public uiLabel string
---@field public uiGadget string
---@field public uiCurve string
---@field public uiRequirement string
---@field public uiOptions GUIContent[]
---@field public uiCurveMin number
---@field public uiCurveMax number
---@field public uiMin number
---@field public uiMax number
---@public
---@return string
function TreeAttribute:ToString() end
