---@class TreeAOSphere
---@field public flag bool
---@field public area number
---@field public radius number
---@field public density number
---@field public position Vector3
---@public
---@param pos Vector3
---@param nor Vector3
---@return number
function TreeAOSphere:PointOcclusion(pos, nor) end
