---@class SplashScreenJson : ValueType
---@field public minOsVersion string
---@field public fileSuffix string
---@field public size string
---@field public hasOrientation bool
---@field public isPortrait bool
---@field public types SplashScreenJson[]
