---@class CullingGroupEvent : ValueType
---@field public index number
---@field public isVisible bool
---@field public wasVisible bool
---@field public hasBecomeVisible bool
---@field public hasBecomeInvisible bool
---@field public currentDistance number
---@field public previousDistance number
