---@class TileData : ValueType
---@field public sprite Sprite
---@field public color Color
---@field public transform Matrix4x4
---@field public gameObject GameObject
---@field public flags number
---@field public colliderType number
