---@class RenderQueueRange : ValueType
---@field public min number
---@field public max number
---@field public all RenderQueueRange
---@field public opaque RenderQueueRange
---@field public transparent RenderQueueRange
