---@class NativeProfilerTimeline_DrawArgs : ValueType
---@field public frameIndex number
---@field public threadIndex number
---@field public timeOffset number
---@field public threadRect Rect
---@field public shownAreaRect Rect
---@field public selectedEntryIndex number
---@field public mousedOverEntryIndex number
---@public
---@return void
function NativeProfilerTimeline_DrawArgs:Reset() end
