---@class StrippingLevel : Enum
---@field public value__ number
---@field public Disabled number
---@field public StripAssemblies number
---@field public StripByteCode number
---@field public UseMicroMSCorlib number
