---@class SceneDependencyInfo : ValueType
---@field public scene string
---@field public processedScene string
---@field public referencedObjects ReadOnlyCollection`1
---@field public globalUsage BuildUsageTagGlobal
