---@class ParticleSystemSortMode : Enum
---@field public value__ number
---@field public None number
---@field public Distance number
---@field public OldestInFront number
---@field public YoungestInFront number
