---@class LocationServiceStatus : Enum
---@field public value__ number
---@field public Stopped number
---@field public Initializing number
---@field public Running number
---@field public Failed number
