---@class MeshTopology : Enum
---@field public value__ number
---@field public Triangles number
---@field public Quads number
---@field public Lines number
---@field public LineStrip number
---@field public Points number
