---@class ModelImporterGenerateAnimations : Enum
---@field public value__ number
---@field public None number
---@field public GenerateAnimations number
---@field public InRoot number
---@field public InOriginalRoots number
---@field public InNodes number
