---@class TimeAreaItem : Control
---@field public headColor Color
---@field public lineColor Color
---@field public drawLine bool
---@field public drawHead bool
---@field public canMoveHead bool
---@field public tooltip string
---@field public boundOffset Vector2
---@field public bounds Rect
---@field public showTooltip bool
---@public
---@param rect Rect
---@param state WindowState
---@param time number
---@return void
function TimeAreaItem:Draw(rect, state, time) end
