---@class TimeCursorManipulator : AnimationWindowManipulator
---@field public alignment number
---@field public headColor Color
---@field public lineColor Color
---@field public dottedLine bool
---@field public drawLine bool
---@field public drawHead bool
---@field public tooltip string
---@public
---@param windowRect Rect
---@param pixelTime number
---@return void
function TimeCursorManipulator:OnGUI(windowRect, pixelTime) end
