---@class ParticleSystemSubEmitterProperties : Enum
---@field public value__ number
---@field public InheritNothing number
---@field public InheritEverything number
---@field public InheritColor number
---@field public InheritSize number
---@field public InheritRotation number
---@field public InheritLifetime number
