---@class LocalNotification
---@field public timeZone string
---@field public repeatCalendar number
---@field public repeatInterval number
---@field public fireDate DateTime
---@field public alertBody string
---@field public alertTitle string
---@field public alertAction string
---@field public alertLaunchImage string
---@field public soundName string
---@field public applicationIconBadgeNumber number
---@field public defaultSoundName string
---@field public userInfo IDictionary
---@field public hasAction bool
