---@class ChildMotion : ValueType
---@field public motion Motion
---@field public threshold number
---@field public position Vector2
---@field public timeScale number
---@field public cycleOffset number
---@field public directBlendParameter string
---@field public mirror bool
