---@class ViewTool : Enum
---@field public value__ number
---@field public None number
---@field public Orbit number
---@field public Pan number
---@field public Zoom number
---@field public FPS number
