---@class StackFrame : ValueType
---@field public lineNumber number
---@field public sourceFile string
---@field public methodName string
---@field public signature string
---@field public moduleName string
