---@class PackedMemorySnapshot
---@field public nativeTypes PackedNativeType[]
---@field public nativeObjects PackedNativeUnityEngineObject[]
---@field public gcHandles PackedGCHandle[]
---@field public connections Connection[]
---@field public managedHeapSections MemorySection[]
---@field public typeDescriptions TypeDescription[]
---@field public virtualMachineInformation VirtualMachineInformation
