---@class ColorUsageAttribute : PropertyAttribute
---@field public showAlpha bool
---@field public hdr bool
---@field public minBrightness number
---@field public maxBrightness number
---@field public minExposureValue number
---@field public maxExposureValue number
