---@class OffMeshLink : Behaviour
---@field public activated bool
---@field public occupied bool
---@field public costOverride number
---@field public biDirectional bool
---@field public navMeshLayer number
---@field public area number
---@field public autoUpdatePositions bool
---@field public startTransform Transform
---@field public endTransform Transform
---@public
---@return void
function OffMeshLink:UpdatePositions() end
