---@class FileType : Enum
---@field public value__ number
---@field public NonAssetType number
---@field public DeprecatedCachedAssetType number
---@field public SerializedAssetType number
---@field public MetaAssetType number
