---@class SketchUpImportCamera : ValueType
---@field public position Vector3
---@field public lookAt Vector3
---@field public up Vector3
---@field public fieldOfView number
---@field public aspectRatio number
---@field public orthoSize number
---@field public isPerspective bool
