---@class JobRanges : ValueType
---@field public BatchSize number
---@field public NumJobs number
---@field public TotalIterationCount number
---@field public NumPhases number
---@field public IndicesPerPhase number
---@field public StartEndIndex IntPtr
---@field public PhaseData IntPtr
