---@class OffMeshLinkData : ValueType
---@field public valid bool
---@field public activated bool
---@field public linkType number
---@field public startPos Vector3
---@field public endPos Vector3
---@field public offMeshLink OffMeshLink
