---@class FFTWindow : Enum
---@field public value__ number
---@field public Rectangular number
---@field public Triangle number
---@field public Hamming number
---@field public Hanning number
---@field public Blackman number
---@field public BlackmanHarris number
