---@class Icon : ValueType
---@field public idiom number
---@field public width number
---@field public height number
---@field public scale number
---@field public xcodefile string
---@field public types Icon[]
