---@class RigidbodyConstraints2D : Enum
---@field public value__ number
---@field public None number
---@field public FreezePositionX number
---@field public FreezePositionY number
---@field public FreezeRotation number
---@field public FreezePosition number
---@field public FreezeAll number
