---@class ApplicationSandboxType : Enum
---@field public value__ number
---@field public Unknown number
---@field public NotSandboxed number
---@field public Sandboxed number
---@field public SandboxBroken number
