---@class ProgressInfo
---@field public jobId number
---@field public title string
---@field public extraInfo string
---@field public currentCount number
---@field public totalCount number
---@field public completed bool
---@field public cancelled bool
---@field public canCancel bool
---@field public lastErrorString string
---@field public lastError number
---@field public percentComplete number
---@field public isProgressTypeCount bool
---@field public isProgressTypePercent bool
---@field public errorOccured bool
