---@class PBXFileType : Enum
---@field public value__ number
---@field public NotBuildable number
---@field public Framework number
---@field public Source number
---@field public Resource number
---@field public CopyFile number
---@field public ShellScript number
