---@class WindZone : Component
---@field public mode number
---@field public radius number
---@field public windMain number
---@field public windTurbulence number
---@field public windPulseMagnitude number
---@field public windPulseFrequency number
