---@class CreationContext : ValueType
---@field public Default CreationContext
---@field public target VisualElement
---@field public visualTreeAsset VisualTreeAsset
---@field public slotInsertionPoints Dictionary`2
