---@class UxmlRootElementFactory : UxmlFactory`2
---@field public uxmlName string
---@field public uxmlQualifiedName string
---@field public substituteForTypeName string
---@field public substituteForTypeNamespace string
---@field public substituteForTypeQualifiedName string
---@public
---@param bag IUxmlAttributes
---@param cc CreationContext
---@return VisualElement
function UxmlRootElementFactory:Create(bag, cc) end
