---@class PlayModeStateChange : Enum
---@field public value__ number
---@field public EnteredEditMode number
---@field public ExitingEditMode number
---@field public EnteredPlayMode number
---@field public ExitingPlayMode number
