---@class XRCameraSubsystemDescriptor : SubsystemDescriptor`1
---@field public ProvidesAverageBrightness bool
---@field public ProvidesAverageColorTemperature bool
---@field public ProvidesProjectionMatrix bool
---@field public ProvidesDisplayMatrix bool
---@field public ProvidesTimestamp bool
