---@class AvatarTarget : Enum
---@field public value__ number
---@field public Root number
---@field public Body number
---@field public LeftFoot number
---@field public RightFoot number
---@field public LeftHand number
---@field public RightHand number
