---@class LightBakingOutput : ValueType
---@field public probeOcclusionLightIndex number
---@field public occlusionMaskChannel number
---@field public lightmapBakeType number
---@field public mixedLightingMode number
---@field public isBaked bool
