---@class NativeProfilerTimeline_GetEntryAtPositionArgs : ValueType
---@field public frameIndex number
---@field public threadIndex number
---@field public timeOffset number
---@field public threadRect Rect
---@field public shownAreaRect Rect
---@field public position Vector2
---@field public out_EntryIndex number
---@field public out_EntryYMaxPos number
---@field public out_EntryName string
---@public
---@return void
function NativeProfilerTimeline_GetEntryAtPositionArgs:Reset() end
