---@class AuthorizationNetwork : Enum
---@field public value__ number
---@field public None number
---@field public Internal number
---@field public Facebook number
---@field public Twitter number
---@field public Google number
---@field public GameCenter number
