---@class CameraType : Enum
---@field public value__ number
---@field public Game number
---@field public SceneView number
---@field public Preview number
---@field public VR number
---@field public Reflection number
