---@class PackageType : Enum
---@field public value__ number
---@field public Unknown number
---@field public PlaybackEngine number
---@field public UnityExtension number
---@field public PackageManager number
