---@class ParticleSystemCurveMode : Enum
---@field public value__ number
---@field public Constant number
---@field public Curve number
---@field public TwoCurves number
---@field public TwoConstants number
