---@class PingData
---@field public m_TimeStart number
---@field public m_ZoomTime number
---@field public m_WaitTime number
---@field public m_FadeOutTime number
---@field public m_PeakScale number
---@field public m_ContentDraw Action`1
---@field public m_ContentRect Rect
---@field public m_AvailableWidth number
---@field public m_PingStyle GUIStyle
---@field public isPinging bool
---@public
---@return void
function PingData:HandlePing() end
