---@class VideoTrackAttributes : ValueType
---@field public frameRate MediaRational
---@field public width number
---@field public height number
---@field public includeAlpha bool
---@field public bitRateMode number
