---@class InvalidStateMachineBehaviour : ScriptableObject
---@field public monoScript MonoScript
---@field public controller AnimatorController
---@field public state AnimatorState
---@field public stateMachine AnimatorStateMachine
---@field public layerIndex number
---@field public behaviourIndex number
