---@class DrawRendererSortSettings : ValueType
---@field public worldToCameraMatrix Matrix4x4
---@field public cameraPosition Vector3
---@field public flags number
---@field public sortOrthographic bool
