---@class TransformAccess : ValueType
---@field public position Vector3
---@field public rotation Quaternion
---@field public localPosition Vector3
---@field public localRotation Quaternion
---@field public localScale Vector3
