---@class NavMeshBuildSource : ValueType
---@field public transform Matrix4x4
---@field public size Vector3
---@field public shape number
---@field public area number
---@field public sourceObject Object
---@field public component Component
