---@class RemoteNotification
---@field public alertBody string
---@field public alertTitle string
---@field public soundName string
---@field public applicationIconBadgeNumber number
---@field public userInfo IDictionary
---@field public hasAction bool
