---@class SegmentGenerationResult : ValueType
---@field public gridIndex GridIndex
---@field public meshFilter MeshFilter
---@field public meshCollider MeshCollider
---@field public success bool
---@field public elapsedTimeSeconds number
