---@class ControllerColliderHit
---@field public controller CharacterController
---@field public collider Collider
---@field public rigidbody Rigidbody
---@field public gameObject GameObject
---@field public transform Transform
---@field public point Vector3
---@field public normal Vector3
---@field public moveDirection Vector3
---@field public moveLength number
