---@class ClusterInputType : Enum
---@field public value__ number
---@field public Button number
---@field public Axis number
---@field public Tracker number
---@field public CustomProvidedInput number
