---@class TileFlags : Enum
---@field public value__ number
---@field public None number
---@field public LockColor number
---@field public LockTransform number
---@field public InstantiateGameObjectRuntimeOnly number
---@field public LockAll number
