---@class GITextureAvailability : Enum
---@field public value__ number
---@field public GITextureUnknown number
---@field public GITextureNotAvailable number
---@field public GITextureLoading number
---@field public GITextureAvailable number
---@field public GITextureAvailabilityCount number
