---@class WrapModeFixed : Enum
---@field public value__ number
---@field public Default number
---@field public Once number
---@field public Loop number
---@field public ClampForever number
---@field public PingPong number
