---@class MeshColliderCookingOptions : Enum
---@field public value__ number
---@field public None number
---@field public InflateConvexMesh number
---@field public CookForFasterSimulation number
---@field public EnableMeshCleaning number
---@field public WeldColocatedVertices number
