---@class Styles
---@field public debugBox GUIStyle
---@field public listBackground GUIStyle
---@field public listElement GUIStyle
---@field public listHeader GUIStyle
---@field public listHelpBox GUIStyle
---@field public infoContainer GUIStyle
---@field public infoHeader GUIStyle
---@field public infoText GUIStyle
---@field public infoReleaseNotesBackground GUIStyle
---@field public infoToggle GUIStyle
---@field public downloadButtonContent GUIContent
---@field public okButtonContent GUIContent
---@field public cancelButtonContent GUIContent
---@field public restartUnityContent GUIContent
---@field public loadedContent GUIContent
---@field public activateContent GUIContent
