---@class CustomRenderTextureUpdateZone : ValueType
---@field public updateZoneCenter Vector3
---@field public updateZoneSize Vector3
---@field public rotation number
---@field public passIndex number
---@field public needSwap bool
