---@class DirectorUpdateMode : Enum
---@field public value__ number
---@field public DSPClock number
---@field public GameTime number
---@field public UnscaledGameTime number
---@field public Manual number
