---@class MaterialGlobalIlluminationFlags : Enum
---@field public value__ number
---@field public None number
---@field public RealtimeEmissive number
---@field public BakedEmissive number
---@field public EmissiveIsBlack number
---@field public AnyEmissive number
