---@class AreaLearningMode : Enum
---@field public value__ number
---@field public None number
---@field public LocalAreaDescriptionWithoutLearning number
---@field public LocalAreaDescription number
---@field public CloudAreaDescription number
