---@class RenderStateMask : Enum
---@field public value__ number
---@field public Nothing number
---@field public Blend number
---@field public Raster number
---@field public Depth number
---@field public Stencil number
---@field public Everything number
