---@class ParticleSystemTriggerEventType : Enum
---@field public value__ number
---@field public Inside number
---@field public Outside number
---@field public Enter number
---@field public Exit number
