---@class ObstacleAvoidanceType : Enum
---@field public value__ number
---@field public NoObstacleAvoidance number
---@field public LowQualityObstacleAvoidance number
---@field public MedQualityObstacleAvoidance number
---@field public GoodQualityObstacleAvoidance number
---@field public HighQualityObstacleAvoidance number
