---@class HeightmapPainter
---@field public size number
---@field public strength number
---@field public targetHeight number
---@field public tool number
---@field public brush Brush
---@field public terrainData TerrainData
---@public
---@param xCenterNormalized number
---@param yCenterNormalized number
---@return void
function HeightmapPainter:PaintHeight(xCenterNormalized, yCenterNormalized) end
