---@class DepthTextureMode : Enum
---@field public value__ number
---@field public None number
---@field public Depth number
---@field public DepthNormals number
---@field public MotionVectors number
