---@class ParticleSystemRenderMode : Enum
---@field public value__ number
---@field public Billboard number
---@field public Stretch number
---@field public HorizontalBillboard number
---@field public VerticalBillboard number
---@field public Mesh number
---@field public None number
