---@class UserState : Enum
---@field public value__ number
---@field public Online number
---@field public OnlineAndAway number
---@field public OnlineAndBusy number
---@field public Offline number
---@field public Playing number
