---@class TouchScreenKeyboard_InternalConstructorHelperArguments : ValueType
---@field public keyboardType number
---@field public autocorrection number
---@field public multiline number
---@field public secure number
---@field public alert number
---@field public characterLimit number
