---@class ContactPoint : ValueType
---@field public point Vector3
---@field public normal Vector3
---@field public thisCollider Collider
---@field public otherCollider Collider
---@field public separation number
