---@class TextureImporterNPOTScale : Enum
---@field public value__ number
---@field public None number
---@field public ToNearest number
---@field public ToLarger number
---@field public ToSmaller number
