---@class SurfaceEffector2D : Effector2D
---@field public speed number
---@field public speedVariation number
---@field public forceScale number
---@field public useContactForce bool
---@field public useFriction bool
---@field public useBounce bool
