---@class iOSStatusBarStyle : Enum
---@field public value__ number
---@field public Default number
---@field public LightContent number
---@field public BlackTranslucent number
---@field public BlackOpaque number
