---@class LookDevProperty : Enum
---@field public value__ number
---@field public ExposureValue number
---@field public HDRI number
---@field public ShadingMode number
---@field public EnvRotation number
---@field public LoDIndex number
---@field public Count number
