---@class AnimatorConditionMode : Enum
---@field public value__ number
---@field public If number
---@field public IfNot number
---@field public Greater number
---@field public Less number
---@field public Equals number
---@field public NotEqual number
