---@class ExportPackageOptions : Enum
---@field public value__ number
---@field public Default number
---@field public Interactive number
---@field public Recurse number
---@field public IncludeDependencies number
---@field public IncludeLibraryAssets number
