---@class RenderingOptions
---@field public nameFilter string
---@field public showSucceeded bool
---@field public showFailed bool
---@field public showIgnored bool
---@field public showNotRunned bool
---@field public categories String[]
