---@class ModelImporterTangents : Enum
---@field public value__ number
---@field public Import number
---@field public CalculateLegacy number
---@field public CalculateLegacyWithSplitTangents number
---@field public CalculateMikk number
---@field public None number
