---@class StyleSheetImportErrorType : Enum
---@field public value__ number
---@field public Syntax number
---@field public Semantic number
---@field public Other number
---@field public Internal number
