---@class TimelineEditor
---@field public inspectedDirector PlayableDirector
---@field public masterDirector PlayableDirector
---@field public inspectedAsset TimelineAsset
---@field public masterAsset TimelineAsset
---@field public playableDirector PlayableDirector
---@field public timelineAsset TimelineAsset
