---@class RenderBufferStoreAction : Enum
---@field public value__ number
---@field public Store number
---@field public Resolve number
---@field public StoreAndResolve number
---@field public DontCare number
