---@class TextureImporterCompression : Enum
---@field public value__ number
---@field public Uncompressed number
---@field public Compressed number
---@field public CompressedHQ number
---@field public CompressedLQ number
