---@class VideoRenderMode : Enum
---@field public value__ number
---@field public CameraFarPlane number
---@field public CameraNearPlane number
---@field public RenderTexture number
---@field public MaterialOverride number
---@field public APIOnly number
