---@class EdgeDebugState : Enum
---@field public value__ number
---@field public Normal number
---@field public SoloSome number
---@field public SoloAll number
---@field public MuteSome number
---@field public MuteAll number
---@field public MuteAndSolo number
