---@class ShaderCompilerData : ValueType
---@field public shaderKeywordSet ShaderKeywordSet
---@field public platformKeywordSet PlatformKeywordSet
---@field public shaderRequirements number
---@field public graphicsTier number
---@field public shaderCompilerPlatform number
