---@class XRExampleSubsystemDescriptor : SubsystemDescriptor`1
---@field public supportsEditorMode bool
---@field public disableBackbufferMSAA bool
---@field public stereoscopicBackbuffer bool
---@field public usePBufferEGL bool
