---@class NativeProfilerTimeline_GetEntryInstanceInfoArgs : ValueType
---@field public frameIndex number
---@field public threadIndex number
---@field public entryIndex number
---@field public out_Id number
---@field public out_Path string
---@field public out_CallstackInfo string
---@field public out_MetaData string
---@public
---@return void
function NativeProfilerTimeline_GetEntryInstanceInfoArgs:Reset() end
