---@class Icons
---@field public s_FailImg Texture2D
---@field public s_IgnoreImg Texture2D
---@field public s_SuccessImg Texture2D
---@field public s_UnknownImg Texture2D
---@field public s_InconclusiveImg Texture2D
---@field public s_StopwatchImg Texture2D
