---@class MatchTargetFields : Enum
---@field public value__ number
---@field public PositionX number
---@field public PositionY number
---@field public PositionZ number
---@field public RotationX number
---@field public RotationY number
---@field public RotationZ number
