---@class MinMaxCurveState : Enum
---@field public value__ number
---@field public k_Scalar number
---@field public k_Curve number
---@field public k_TwoCurves number
---@field public k_TwoScalars number
