---@class LookDevMode : Enum
---@field public value__ number
---@field public Single1 number
---@field public Single2 number
---@field public SideBySide number
---@field public Split number
---@field public Zone number
---@field public Count number
