---@class UIOrientation : Enum
---@field public value__ number
---@field public Portrait number
---@field public PortraitUpsideDown number
---@field public LandscapeRight number
---@field public LandscapeLeft number
---@field public AutoRotation number
