---@class DetailMeshWizard : TerrainWizard
---@field public m_Detail GameObject
---@field public m_NoiseSpread number
---@field public m_MinWidth number
---@field public m_MaxWidth number
---@field public m_MinHeight number
---@field public m_MaxHeight number
---@field public m_HealthyColor Color
---@field public m_DryColor Color
---@field public m_RenderMode number
---@public
---@return void
function DetailMeshWizard:OnEnable() end
