---@class ParticleSystemStopAction : Enum
---@field public value__ number
---@field public None number
---@field public Disable number
---@field public Destroy number
---@field public Callback number
