---@class ModelImporterMaterialName : Enum
---@field public value__ number
---@field public BasedOnTextureName number
---@field public BasedOnMaterialName number
---@field public BasedOnModelNameAndMaterialName number
---@field public BasedOnTextureName_Or_ModelNameAndMaterialName number
