---@class HorizontalOrVerticalLayoutGroup : LayoutGroup
---@field public spacing number
---@field public childForceExpandWidth bool
---@field public childForceExpandHeight bool
---@field public childControlWidth bool
---@field public childControlHeight bool
