---@class OperationStatus
---@field public id string
---@field public status number
---@field public type string
---@field public packageList PackageInfo[]
---@field public progress number
---@field public error Error
