---@class DevDevice : ValueType
---@field public id string
---@field public name string
---@field public type string
---@field public module string
---@field public state number
---@field public features number
---@field public isConnected bool
---@field public none DevDevice
---@public
---@return string
function DevDevice:ToString() end
