---@class ProfilerCaptureFlags : Enum
---@field public value__ number
---@field public None number
---@field public Channels number
---@field public DSPNodes number
---@field public Clips number
---@field public All number
