---@class LightProbeUsage : Enum
---@field public value__ number
---@field public Off number
---@field public BlendProbes number
---@field public UseProxyVolume number
---@field public CustomProvided number
