---@class LightProbeProxyVolume : Behaviour
---@field public isFeatureSupported bool
---@field public boundsGlobal Bounds
---@field public sizeCustom Vector3
---@field public originCustom Vector3
---@field public probeDensity number
---@field public gridResolutionX number
---@field public gridResolutionY number
---@field public gridResolutionZ number
---@field public boundingBoxMode number
---@field public resolutionMode number
---@field public probePositionMode number
---@field public refreshMode number
---@field public qualityMode number
---@public
---@return void
function LightProbeProxyVolume:Update() end
