---@class NativeInputUpdateType : Enum
---@field public value__ number
---@field public Dynamic number
---@field public Fixed number
---@field public BeforeRender number
---@field public Editor number
---@field public IgnoreFocus number
