---@class PlayerLoopSystem : ValueType
---@field public type Type
---@field public subSystemList PlayerLoopSystem[]
---@field public updateDelegate UpdateFunction
---@field public updateFunction IntPtr
---@field public loopConditionFunction IntPtr
