---@class AndroidDeploymentTargetRequirements : DeploymentTargetRequirements
---@field public minSdkVersion number
---@field public glesMinRequired number
---@field public openGLRequireES31AEP bool
---@field public requireVulkan bool
---@field public targetArchitectures number
