---@class SegmentGenerationRequest : ValueType
---@field public gridIndex GridIndex
---@field public destinationMeshFilter MeshFilter
---@field public destinationMeshCollider MeshCollider
---@field public provideNormals bool
---@field public provideColors bool
---@field public providePhysics bool
