---@class AudioImporterSampleSettings : ValueType
---@field public loadType number
---@field public sampleRateSetting number
---@field public sampleRateOverride number
---@field public compressionFormat number
---@field public quality number
---@field public conversionMode number
