---@class PositionalLocatorState : Enum
---@field public value__ number
---@field public Unavailable number
---@field public OrientationOnly number
---@field public Activating number
---@field public Active number
---@field public Inhibited number
