---@class ParticleSystemSubEmitterType : Enum
---@field public value__ number
---@field public Birth number
---@field public Collision number
---@field public Death number
---@field public Trigger number
---@field public Manual number
