---@class HolographicStreamerConnectionFailureReason : Enum
---@field public value__ number
---@field public None number
---@field public Unknown number
---@field public Unreachable number
---@field public HandshakeFailed number
---@field public ProtocolVersionMismatch number
---@field public ConnectionLost number
