---@class RenderQueue : Enum
---@field public value__ number
---@field public Background number
---@field public Geometry number
---@field public AlphaTest number
---@field public GeometryLast number
---@field public Transparent number
---@field public Overlay number
