---@class Blackboard : GraphElement
---@field public addItemRequested Action`1
---@field public moveItemRequested Action`3
---@field public editTextRequested Action`3
---@field public title string
---@field public subTitle string
---@field public contentContainer VisualElement
---@field public scrollable bool
