---@class KeyIdentifier
---@field public curve AnimationCurve
---@field public curveId number
---@field public key number
---@field public binding EditorCurveBinding
---@field public keyframe Keyframe
