---@class ProfilerMemoryRecordMode : Enum
---@field public value__ number
---@field public None number
---@field public ManagedAllocations number
---@field public AllAllocationsFast number
---@field public AllAllocationsFull number
