---@class AndroidShowActivityIndicatorOnLoading : Enum
---@field public value__ number
---@field public Large number
---@field public InversedLarge number
---@field public Small number
---@field public InversedSmall number
---@field public DontShow number
