---@class Allocator : Enum
---@field public value__ number
---@field public Invalid number
---@field public None number
---@field public Temp number
---@field public TempJob number
---@field public Persistent number
