---@class JointLimitState2D : Enum
---@field public value__ number
---@field public Inactive number
---@field public LowerLimit number
---@field public UpperLimit number
---@field public EqualLimits number
