---@class CombineInstance : ValueType
---@field public mesh Mesh
---@field public subMeshIndex number
---@field public transform Matrix4x4
---@field public lightmapScaleOffset Vector4
---@field public realtimeLightmapScaleOffset Vector4
