---@class MatchInfoSnapshot
---@field public networkId number
---@field public hostNodeId number
---@field public name string
---@field public averageEloScore number
---@field public maxSize number
---@field public currentSize number
---@field public isPrivate bool
---@field public matchAttributes Dictionary`2
---@field public directConnectInfos List`1
