---@class AdditionalCanvasShaderChannels : Enum
---@field public value__ number
---@field public None number
---@field public TexCoord1 number
---@field public TexCoord2 number
---@field public TexCoord3 number
---@field public Normal number
---@field public Tangent number
