---@class ValueTypePopup : Enum
---@field public value__ number
---@field public STRING number
---@field public FLOAT number
---@field public LONG number
---@field public INT32 number
---@field public BOOLEAN number
---@field public ENUM number
