---@class XboxOneDeployMethod : Enum
---@field public value__ number
---@field public Push number
---@field public Pull number
---@field public RunFromPC number
---@field public Package number
---@field public PackageStreaming number
