---@class CustomGridBrushAttribute : Attribute
---@field public hideAssetInstances bool
---@field public hideDefaultInstance bool
---@field public defaultBrush bool
---@field public defaultName string
