---@class WebGLExceptionSupport : Enum
---@field public value__ number
---@field public None number
---@field public ExplicitlyThrownExceptionsOnly number
---@field public FullWithoutStacktrace number
---@field public FullWithStacktrace number
