---@class TransparencySortMode : Enum
---@field public value__ number
---@field public Default number
---@field public Perspective number
---@field public Orthographic number
---@field public CustomAxis number
