---@class SkeletonBone : ValueType
---@field public name string
---@field public position Vector3
---@field public rotation Quaternion
---@field public scale Vector3
---@field public transformModified number
