---@class StyleValueKeyword : Enum
---@field public value__ number
---@field public Inherit number
---@field public Auto number
---@field public Unset number
---@field public True number
---@field public False number
---@field public None number
