---@class ImportRawHeightmap : TerrainWizard
---@field public m_Depth number
---@field public m_Width number
---@field public m_Height number
---@field public m_ByteOrder number
---@field public m_FlipVertically bool
---@field public m_TerrainSize Vector3
