---@class BuoyancyEffector2D : Effector2D
---@field public surfaceLevel number
---@field public density number
---@field public linearDrag number
---@field public angularDrag number
---@field public flowAngle number
---@field public flowMagnitude number
---@field public flowVariation number
