---@class LineTextureMode : Enum
---@field public value__ number
---@field public Stretch number
---@field public Tile number
---@field public DistributePerSegment number
---@field public RepeatPerSegment number
