---@class AssetStoreAsset
---@field public id number
---@field public name string
---@field public displayName string
---@field public staticPreviewURL string
---@field public dynamicPreviewURL string
---@field public className string
---@field public price string
---@field public packageID number
---@field public previewImage Texture2D
---@field public Preview Object
---@field public HasLivePreview bool
---@public
---@return void
function AssetStoreAsset:Dispose() end
