---@class iOSLaunchScreenType : Enum
---@field public value__ number
---@field public Default number
---@field public ImageAndBackgroundRelative number
---@field public CustomXib number
---@field public None number
---@field public ImageAndBackgroundConstant number
