---@class AudioProfilerClipInfo : ValueType
---@field public assetInstanceId number
---@field public assetNameOffset number
---@field public loadState number
---@field public internalLoadState number
---@field public age number
---@field public disposed number
---@field public numChannelInstances number
