---@class ModelImporterNormalCalculationMode : Enum
---@field public value__ number
---@field public Unweighted_Legacy number
---@field public Unweighted number
---@field public AreaWeighted number
---@field public AngleWeighted number
---@field public AreaAndAngleWeighted number
