---@class TilemapRenderer : Renderer
---@field public chunkSize Vector3Int
---@field public chunkCullingBounds Vector3
---@field public maxChunkCount number
---@field public maxFrameAge number
---@field public sortOrder number
---@field public detectChunkCullingBounds number
---@field public maskInteraction number
