---@class ColorWriteMask : Enum
---@field public value__ number
---@field public Alpha number
---@field public Blue number
---@field public Green number
---@field public Red number
---@field public All number
