---@class ObjectListAreaState
---@field public m_SelectedInstanceIDs List`1
---@field public m_LastClickedInstanceID number
---@field public m_HadKeyboardFocusLastEvent bool
---@field public m_ExpandedInstanceIDs List`1
---@field public m_RenameOverlay RenameOverlay
---@field public m_CreateAssetUtility CreateAssetUtility
---@field public m_NewAssetIndexInList number
---@field public m_ScrollPosition Vector2
---@field public m_GridSize number
---@public
---@return void
function ObjectListAreaState:OnAwake() end
