---@class WSASDK : Enum
---@field public value__ number
---@field public SDK80 number
---@field public SDK81 number
---@field public PhoneSDK81 number
---@field public UniversalSDK81 number
---@field public UWP number
