---@class IMouseEvent
---@field public modifiers number
---@field public mousePosition Vector2
---@field public localMousePosition Vector2
---@field public mouseDelta Vector2
---@field public clickCount number
---@field public button number
---@field public shiftKey bool
---@field public ctrlKey bool
---@field public commandKey bool
---@field public altKey bool
