---@class IvyInfo
---@field public Version PackageVersion
---@field public Organisation string
---@field public Module string
---@field public Revision string
---@field public Branch string
---@field public Status string
---@field public Publication string
---@field public Type number
---@field public UnityVersion PackageVersion
---@field public Title string
---@field public Description string
---@field public Published bool
---@field public Repositories List`1
---@field public FullName string
---@public
---@return IvyInfo
function IvyInfo:Clone() end
