---@class BlendTreeType : Enum
---@field public value__ number
---@field public Simple1D number
---@field public SimpleDirectional2D number
---@field public FreeformDirectional2D number
---@field public FreeformCartesian2D number
---@field public Direct number
