---@class TextGenerationError : Enum
---@field public value__ number
---@field public None number
---@field public CustomSizeOnNonDynamicFont number
---@field public CustomStyleOnNonDynamicFont number
---@field public NoFont number
