---@class AnimationWindowHierarchyNode : TreeViewItem
---@field public path string
---@field public animatableObjectType Type
---@field public propertyName string
---@field public binding Nullable`1
---@field public curves AnimationWindowCurve[]
---@field public topPixel Nullable`1
---@field public indent number
