---@class SplatPainter
---@field public size number
---@field public strength number
---@field public brush Brush
---@field public target number
---@field public terrainData TerrainData
---@field public tool number
---@public
---@param xCenterNormalized number
---@param yCenterNormalized number
---@param splatIndex number
---@return void
function SplatPainter:Paint(xCenterNormalized, yCenterNormalized, splatIndex) end
