---@class LightmapData
---@field public lightmapLight Texture2D
---@field public lightmapColor Texture2D
---@field public lightmapDir Texture2D
---@field public shadowMask Texture2D
---@field public lightmap Texture2D
---@field public lightmapFar Texture2D
---@field public lightmapNear Texture2D
