---@class ImageResizing
---@field public type number
---@field public left number
---@field public right number
---@field public top number
---@field public bottom number
---@field public centerResizeMode number
---@field public centerWidth number
---@field public centerHeight number
