---@class MonoIsland : ValueType
---@field public _target number
---@field public _development_player bool
---@field public _editor bool
---@field public _allowUnsafeCode bool
---@field public _api_compatibility_level number
---@field public _files String[]
---@field public _references String[]
---@field public _defines String[]
---@field public _output string
---@public
---@return string
function MonoIsland:GetExtensionOfSourceFiles() end
