---@class ObjectMemoryInfo
---@field public instanceId number
---@field public memorySize number
---@field public count number
---@field public reason number
---@field public name string
---@field public className string
