---@class GameViewRenderMode : Enum
---@field public value__ number
---@field public LeftEye number
---@field public RightEye number
---@field public BothEyes number
---@field public OcclusionMesh number
