---@class MatchInfo
---@field public address string
---@field public port number
---@field public domain number
---@field public networkId number
---@field public accessToken NetworkAccessToken
---@field public nodeId number
---@field public usingRelay bool
---@public
---@return string
function MatchInfo:ToString() end
