---@class LightmapSettings : Object
---@field public lightmaps LightmapData[]
---@field public lightmapsMode number
---@field public lightProbes LightProbes
---@field public lightmapsModeLegacy number
---@field public bakedColorSpace number
