---@class NavMeshBuildSourceShape : Enum
---@field public value__ number
---@field public Mesh number
---@field public Terrain number
---@field public Box number
---@field public Sphere number
---@field public Capsule number
---@field public ModifierBox number
