---@class SpriteAtlasTextureSettings : ValueType
---@field public anisoLevel number
---@field public filterMode number
---@field public generateMipMaps bool
---@field public readable bool
---@field public sRGB bool
