---@class WheelFrictionCurve : ValueType
---@field public extremumSlip number
---@field public extremumValue number
---@field public asymptoteSlip number
---@field public asymptoteValue number
---@field public stiffness number
