---@class PrimitiveType : Enum
---@field public value__ number
---@field public Sphere number
---@field public Capsule number
---@field public Cylinder number
---@field public Cube number
---@field public Plane number
---@field public Quad number
