---@class LightmapsMode : Enum
---@field public value__ number
---@field public NonDirectional number
---@field public CombinedDirectional number
---@field public SeparateDirectional number
---@field public Single number
---@field public Dual number
---@field public Directional number
