---@class GameViewSize
---@field public baseText string
---@field public sizeType number
---@field public width number
---@field public height number
---@field public isFreeAspectRatio bool
---@field public aspectRatio number
---@field public displayText string
---@public
---@param other GameViewSize
---@return void
function GameViewSize:Set(other) end
