---@class CanvasUpdate : Enum
---@field public value__ number
---@field public Prelayout number
---@field public Layout number
---@field public PostLayout number
---@field public PreRender number
---@field public LatePreRender number
---@field public MaxUpdateValue number
