---@class TimelineSceneInfo
---@field public trackCount Dictionary`2
---@field public userTrackTypesCount Dictionary`2
---@field public uniqueDirectors HashSet`1
---@field public numTracks number
---@field public minDuration number
---@field public maxDuration number
---@field public minNumTracks number
---@field public maxNumTracks number
---@field public numRecorded number
