---@class PlaymodeTestsControllerSettings
---@field public filter TestRunnerFilter
---@field public sceneBased bool
---@field public originalScene string
---@field public bootstrapScene string
---@field public resultFilePath string
---@field public isBatchModeRun bool
---@public
---@param filter TestRunnerFilter
---@return PlaymodeTestsControllerSettings
function PlaymodeTestsControllerSettings.CreateRunnerSettings(filter) end
