---@class IvyModule : XmlSerializable
---@field public Timestamp string
---@field public BasePath string
---@field public Selected bool
---@field public Info IvyInfo
---@field public Artifacts IvyArtifacts
---@field public Dependencies IvyDependencies
