---@class AssetBundleBuild : ValueType
---@field public assetBundleName string
---@field public assetBundleVariant string
---@field public assetNames String[]
---@field public addressableNames String[]
