---@class LineRendererEditorSettings : ScriptableSingleton`1
---@field public showSimplifyPreview bool
---@field public createPointSeparation number
---@field public creationOffset number
---@field public inputMode number
---@field public raycastMask LayerMask
---@field public showWireframe bool
---@field public simplifyTolerance number
