---@class ShaderType : Enum
---@field public value__ number
---@field public Vertex number
---@field public Fragment number
---@field public Geometry number
---@field public Hull number
---@field public Domain number
