---@class NetworkEventType : Enum
---@field public value__ number
---@field public DataEvent number
---@field public ConnectEvent number
---@field public DisconnectEvent number
---@field public Nothing number
---@field public BroadcastEvent number
