---@class DeploymentTargetStatus : Enum
---@field public value__ number
---@field public Ready number
---@field public NotReady number
---@field public Unavailable number
---@field public Unknown number
