---@class Align : Enum
---@field public value__ number
---@field public Auto number
---@field public FlexStart number
---@field public Center number
---@field public FlexEnd number
---@field public Stretch number
