---@class TargetJoint2D : Joint2D
---@field public anchor Vector2
---@field public target Vector2
---@field public autoConfigureTarget bool
---@field public maxForce number
---@field public dampingRatio number
---@field public frequency number
