---@class AudioLowPassFilter : Behaviour
---@field public cutoffFrequency number
---@field public customCutoffCurve AnimationCurve
---@field public lowpassResonanceQ number
---@field public lowpassResonaceQ number
