---@class LightShadowResolution : Enum
---@field public value__ number
---@field public FromQualitySettings number
---@field public Low number
---@field public Medium number
---@field public High number
---@field public VeryHigh number
