---@class ErrorCode : Enum
---@field public value__ number
---@field public Unknown number
---@field public NotFound number
---@field public Forbidden number
---@field public InvalidParameter number
---@field public Conflict number
