---@class RenderingPath : Enum
---@field public value__ number
---@field public UsePlayerSettings number
---@field public VertexLit number
---@field public Forward number
---@field public DeferredLighting number
---@field public DeferredShading number
