---@class YogaLogLevel : Enum
---@field public value__ number
---@field public Error number
---@field public Warn number
---@field public Info number
---@field public Debug number
---@field public Verbose number
---@field public Fatal number
