---@class GameObjectTreeViewItem : TreeViewItem
---@field public displayName string
---@field public colorCode number
---@field public objectPPTR Object
---@field public shouldDisplay bool
---@field public isSceneHeader bool
---@field public scene Scene
