---@class iOSEditorPrefKeys
---@field public kDefaultiOSAutomaticallySignBuild string
---@field public kDefaultiOSAutomaticSignTeamId string
---@field public kDefaultiOSProvisioningProfileUUID string
---@field public kDefaulttvOSProvisioningProfileUUID string
---@field public kDefaultiOSProvisioningProfileType string
---@field public kDefaulttvOSProvisioningProfileType string
