---@class VideoAspectRatio : Enum
---@field public value__ number
---@field public NoScaling number
---@field public FitVertically number
---@field public FitHorizontally number
---@field public FitInside number
---@field public FitOutside number
---@field public Stretch number
