---@class TestFinishedMessage : Message
---@field public name string
---@field public state number
---@field public message string
---@field public duration number
---@field public durationMicroseconds number
