---@class AnalyticsEventParam
---@field public requirementType number
---@field public groupID string
---@field public valueProperty ValueProperty
---@field public name string
---@field public value Object
