---@class LocationInfo : ValueType
---@field public latitude number
---@field public longitude number
---@field public altitude number
---@field public horizontalAccuracy number
---@field public verticalAccuracy number
---@field public timestamp number
