---@class ImportAssetOptions : Enum
---@field public value__ number
---@field public Default number
---@field public ForceUpdate number
---@field public ForceSynchronousImport number
---@field public ImportRecursive number
---@field public DontDownloadFromCacheServer number
---@field public ForceUncompressedImport number
