---@class ReflectionProbeSortOptions : Enum
---@field public value__ number
---@field public None number
---@field public Importance number
---@field public Size number
---@field public ImportanceThenSize number
