---@class IconKind : Enum
---@field public value__ number
---@field public Any number
---@field public Application number
---@field public Settings number
---@field public Notification number
---@field public Spotlight number
---@field public Store number
