---@class StaticAccessorType : Enum
---@field public value__ number
---@field public Dot number
---@field public Arrow number
---@field public DoubleColon number
---@field public ArrowWithDefaultReturnIfNull number
