---@class CloudProjectSettings
---@field public userId string
---@field public userName string
---@field public accessToken string
---@field public projectId string
---@field public projectName string
---@field public organizationId string
---@field public organizationName string
