---@class TakeInfo : ValueType
---@field public name string
---@field public defaultClipName string
---@field public startTime number
---@field public stopTime number
---@field public bakeStartTime number
---@field public bakeStopTime number
---@field public sampleRate number
