---@class MinMaxGradientState : Enum
---@field public value__ number
---@field public k_Color number
---@field public k_Gradient number
---@field public k_RandomBetweenTwoColors number
---@field public k_RandomBetweenTwoGradients number
---@field public k_RandomColor number
