---@class IAutomatedUIElement
---@field public name string
---@field public children IList`1
---@field public parent IAutomatedUIElement
---@field public hasRect bool
---@field public rect Rect
---@field public enabled bool
---@field public style GUIStyle
---@field public guiContent GUIContent
