---@class TransitionInterruptionSource : Enum
---@field public value__ number
---@field public None number
---@field public Source number
---@field public Destination number
---@field public SourceThenDestination number
---@field public DestinationThenSource number
