---@class SurfaceData : ValueType
---@field public id SurfaceId
---@field public outputMesh MeshFilter
---@field public outputAnchor WorldAnchor
---@field public outputCollider MeshCollider
---@field public trianglesPerCubicMeter number
---@field public bakeCollider bool
