---@class SpriteRect
---@field public name string
---@field public pivot Vector2
---@field public alignment number
---@field public border Vector4
---@field public rect Rect
---@field public spriteID GUID
---@public
---@param sp SerializedProperty
---@return GUID
function SpriteRect.GetSpriteIDFromSerializedProperty(sp) end
