---@class RelativeJoint2D : Joint2D
---@field public maxForce number
---@field public maxTorque number
---@field public correctionScale number
---@field public autoConfigureOffset bool
---@field public linearOffset Vector2
---@field public angularOffset number
---@field public target Vector2
