---@class ListViewOptions : Enum
---@field public value__ number
---@field public wantsReordering number
---@field public wantsExternalFiles number
---@field public wantsToStartCustomDrag number
---@field public wantsToAcceptCustomDrag number
