---@class RotationOrder : Enum
---@field public value__ number
---@field public OrderXYZ number
---@field public OrderXZY number
---@field public OrderYZX number
---@field public OrderYXZ number
---@field public OrderZXY number
---@field public OrderZYX number
