---@class BoneState : Enum
---@field public value__ number
---@field public None number
---@field public NotFound number
---@field public Duplicate number
---@field public InvalidHierarchy number
---@field public BoneLenghtIsZero number
---@field public Valid number
