---@class NavMeshLinkData : ValueType
---@field public startPosition Vector3
---@field public endPosition Vector3
---@field public costModifier number
---@field public bidirectional bool
---@field public width number
---@field public area number
---@field public agentTypeID number
