---@class PlatformIconStruct : ValueType
---@field public m_Width number
---@field public m_Height number
---@field public m_Kind number
---@field public m_SubKind string
---@field public m_Textures Texture2D[]
