---@class GraphicsRequirement
---@field public Key string
---@field public Any string
---@field public Metal1v2 string
---@field public Metal2v2 string
---@field public Metal2v3 string
---@field public Metal3v1 string
---@field public Metal3v2 string
---@field public Metal4v1 string
