---@class FalloffType : Enum
---@field public value__ number
---@field public InverseSquared number
---@field public InverseSquaredNoRangeAttenuation number
---@field public Linear number
---@field public Legacy number
---@field public Undefined number
