---@class IAPTransaction : ValueType
---@field public transactionContext string
---@field public price number
---@field public itemId string
---@field public itemType string
---@field public level string
---@field public transactionId string
