---@class MeshCollider : Collider
---@field public sharedMesh Mesh
---@field public convex bool
---@field public inflateMesh bool
---@field public cookingOptions number
---@field public skinWidth number
---@field public smoothSphereCollisions bool
