---@class InputEvent : Enum
---@field public value__ number
---@field public None number
---@field public DragEnter number
---@field public DragExit number
---@field public Drag number
---@field public KeyboardInput number
