---@class TextureGenerationOutput : ValueType
---@field public texture Texture2D
---@field public importInspectorWarnings string
---@field public importWarnings String[]
---@field public thumbNail Texture2D
---@field public sprites Sprite[]
