---@class ProfilerAudioView : Enum
---@field public value__ number
---@field public Stats number
---@field public Channels number
---@field public Groups number
---@field public ChannelsAndGroups number
---@field public DSPGraph number
---@field public Clips number
