---@class SpritePackerMode : Enum
---@field public value__ number
---@field public Disabled number
---@field public BuildTimeOnly number
---@field public AlwaysOn number
---@field public BuildTimeOnlyAtlas number
---@field public AlwaysOnAtlas number
