---@class BindType : Enum
---@field public value__ number
---@field public Unbound number
---@field public Float number
---@field public Bool number
---@field public GameObjectActive number
---@field public Int number
---@field public DiscreetInt number
