---@class IMGUIPropertyInstruction : ValueType
---@field public targetTypeName string
---@field public path string
---@field public rect Rect
---@field public beginStacktrace StackFrame[]
---@field public endStacktrace StackFrame[]
