---@class TimelineItemGUI
---@field public zOrder number
---@field public visible bool
---@field public item ITimelineItem
---@field public parentTrackGUI TimelineTrackGUI
---@field public rect Rect
---@field public clippedRect Rect
---@field public boundingRect Rect
