---@class PhraseRecognizedEventArgs : ValueType
---@field public confidence number
---@field public semanticMeanings SemanticMeaning[]
---@field public text string
---@field public phraseStartTime DateTime
---@field public phraseDuration TimeSpan
