---@class VRDeviceInfoEditor : ValueType
---@field public deviceNameKey string
---@field public deviceNameUI string
---@field public externalPluginName string
---@field public supportsEditorMode bool
---@field public inListByDefault bool
