---@class PseudoStates : Enum
---@field public value__ number
---@field public Active number
---@field public Hover number
---@field public Checked number
---@field public Selected number
---@field public Disabled number
---@field public Focus number
