---@class AudioSampleRateSetting : Enum
---@field public value__ number
---@field public PreserveSampleRate number
---@field public OptimizeSampleRate number
---@field public OverrideSampleRate number
