---@class SpeedTreeImporter : AssetImporter
---@field public windQualityNames String[]
---@field public hasImported bool
---@field public materialFolderPath string
---@field public scaleFactor number
---@field public mainColor Color
---@field public specColor Color
---@field public shininess number
---@field public hueVariation Color
---@field public alphaTestRef number
---@field public hasBillboard bool
---@field public enableSmoothLODTransition bool
---@field public animateCrossFading bool
---@field public billboardTransitionCrossFadeWidth number
---@field public fadeOutWidth number
---@field public LODHeights Single[]
---@field public castShadows Boolean[]
---@field public receiveShadows Boolean[]
---@field public useLightProbes Boolean[]
---@field public reflectionProbeUsages ReflectionProbeUsage[]
---@field public enableBump Boolean[]
---@field public enableHue Boolean[]
---@field public bestWindQuality number
---@field public windQualities Int32[]
---@public
---@return void
function SpeedTreeImporter:GenerateMaterials() end
