---@class HolographicAutomation
---@field public simulatedBody SimulatedBody
---@field public simulatedHead SimulatedHead
---@field public simulatedLeftHand SimulatedHand
---@field public simulatedRightHand SimulatedHand
