---@class NormalizedCompilerStatusCode : Enum
---@field public value__ number
---@field public NotNormalized number
---@field public MemberNotFound number
---@field public UnknownTypeOrNamespace number
