---@class AnimationWindowStyles
---@field public pointIcon Texture2D
---@field public playContent GUIContent
---@field public recordContent GUIContent
---@field public previewContent GUIContent
---@field public prevKeyContent GUIContent
---@field public nextKeyContent GUIContent
---@field public firstKeyContent GUIContent
---@field public lastKeyContent GUIContent
---@field public addKeyframeContent GUIContent
---@field public addEventContent GUIContent
---@field public sequencerLinkContent GUIContent
---@field public noAnimatableObjectSelectedText GUIContent
---@field public formatIsMissing GUIContent
---@field public animatorAndAnimationClip GUIContent
---@field public animationClip GUIContent
---@field public create GUIContent
---@field public dopesheet GUIContent
---@field public curves GUIContent
---@field public samples GUIContent
---@field public createNewClip GUIContent
---@field public animatorOptimizedText GUIContent
---@field public playHead GUIStyle
---@field public curveEditorBackground GUIStyle
---@field public curveEditorLabelTickmarks GUIStyle
---@field public eventBackground GUIStyle
---@field public eventTooltip GUIStyle
---@field public eventTooltipArrow GUIStyle
---@field public keyframeBackground GUIStyle
---@field public timelineTick GUIStyle
---@field public dopeSheetKeyframe GUIStyle
---@field public dopeSheetBackground GUIStyle
---@field public popupCurveDropdown GUIStyle
---@field public popupCurveEditorBackground GUIStyle
---@field public popupCurveEditorSwatch GUIStyle
---@field public popupCurveSwatchBackground GUIStyle
---@field public miniToolbar GUIStyle
---@field public miniToolbarButton GUIStyle
---@field public toolbarLabel GUIStyle
---@public
---@return void
function AnimationWindowStyles.Initialize() end
