---@class TrackViewModelData
---@field public DefaultinlineAnimationCurveHeight number
---@field public collapsed bool
---@field public showInlineCurves bool
---@field public inlineAnimationCurveHeight number
