---@class ModelImporterAnimationCompression : Enum
---@field public value__ number
---@field public Off number
---@field public KeyframeReduction number
---@field public KeyframeReductionAndCompression number
---@field public Optimal number
