---@class FrameDebuggerBlendState : ValueType
---@field public writeMask number
---@field public srcBlend number
---@field public dstBlend number
---@field public srcBlendAlpha number
---@field public dstBlendAlpha number
---@field public blendOp number
---@field public blendOpAlpha number
