---@class UserPresenceState : Enum
---@field public value__ number
---@field public Unsupported number
---@field public NotPresent number
---@field public Present number
---@field public Unknown number
