---@class SpriteShapeMetaData : ValueType
---@field public height number
---@field public bevelCutoff number
---@field public bevelSize number
---@field public spriteIndex number
---@field public corner bool
