---@class FingerDof : Enum
---@field public value__ number
---@field public ProximalDownUp number
---@field public ProximalInOut number
---@field public IntermediateCloseOpen number
---@field public DistalCloseOpen number
---@field public LastFingerDof number
