---@class Compass
---@field public magneticHeading number
---@field public trueHeading number
---@field public headingAccuracy number
---@field public rawVector Vector3
---@field public timestamp number
---@field public enabled bool
