---@class VirtualMachineInformation : ValueType
---@field public pointerSize number
---@field public objectHeaderSize number
---@field public arrayHeaderSize number
---@field public arrayBoundsOffsetInHeader number
---@field public arraySizeOffsetInHeader number
---@field public allocationGranularity number
---@field public heapFormatVersion number
