---@class SpecialNames
---@field public kTargetSlotName string
---@field public kFunctionOutSlotName string
---@field public kVarInSlotName string
---@field public kVarOutSlotName string
---@field public kFunctionInSlotName string
