---@class RenderStateBlock : ValueType
---@field public blendState BlendState
---@field public rasterState RasterState
---@field public depthState DepthState
---@field public stencilState StencilState
---@field public stencilReference number
---@field public mask number
