---@class NativeInputEventType : Enum
---@field public value__ number
---@field public DeviceRemoved number
---@field public DeviceConfigChanged number
---@field public Text number
---@field public State number
---@field public Delta number
