---@class BuildCompression : ValueType
---@field public DefaultUncompressed BuildCompression
---@field public DefaultLZ4 BuildCompression
---@field public DefaultLZMA BuildCompression
---@field public compression number
---@field public level number
---@field public blockSize number
