---@class IScore
---@field public leaderboardID string
---@field public value number
---@field public date DateTime
---@field public formattedValue string
---@field public userID string
---@field public rank number
---@public
---@param callback Action`1
---@return void
function IScore:ReportScore(callback) end
