---@class StaticOcclusionCullingVisualization
---@field public showOcclusionCulling bool
---@field public showPreVisualization bool
---@field public showViewVolumes bool
---@field public showDynamicObjectBounds bool
---@field public showPortals bool
---@field public showVisibilityLines bool
---@field public showGeometryCulling bool
---@field public isPreviewOcclusionCullingCameraInPVS bool
---@field public previewOcclusionCamera Camera
---@field public previewOcclucionCamera Camera
