---@class ShareType : Enum
---@field public value__ number
---@field public None number
---@field public TextOnly number
---@field public Image number
---@field public Video number
---@field public Invite number
---@field public Achievement number
