---@class ParticleSystemRenderSpace : Enum
---@field public value__ number
---@field public View number
---@field public World number
---@field public Local number
---@field public Facing number
---@field public Velocity number
