---@class AnimatorCullingMode : Enum
---@field public value__ number
---@field public AlwaysAnimate number
---@field public CullUpdateTransforms number
---@field public CullCompletely number
---@field public BasedOnRenderers number
