---@class AnimationOffsetMenu
---@field public MatchPreviousMenuItem GUIContent
---@field public MatchNextMenuItem GUIContent
---@field public MatchFieldsPrefix string
---@field public ResetOffsetMenuItem GUIContent
---@public
---@param state WindowState
---@param clips TimelineClip[]
---@param menu GenericMenu
---@return void
function AnimationOffsetMenu.OnClipMenu(state, clips, menu) end
