---@class NativePointCloud : ValueType
---@field public version number
---@field public timestamp number
---@field public numPoints number
---@field public points IntPtr
---@field public nativePtr IntPtr
