---@class StateInfoIndex : Enum
---@field public value__ number
---@field public CurrentState number
---@field public NextState number
---@field public ExitState number
---@field public InterruptedState number
