---@class TypeInferenceRules : Enum
---@field public value__ number
---@field public TypeReferencedByFirstArgument number
---@field public TypeReferencedBySecondArgument number
---@field public ArrayOfTypeReferencedByFirstArgument number
---@field public TypeOfFirstArgument number
