---@class DirectionalLight : ValueType
---@field public instanceID number
---@field public shadow bool
---@field public mode number
---@field public direction Vector3
---@field public color LinearColor
---@field public indirectColor LinearColor
---@field public penumbraWidthRadian number
