---@class VideoImporterTargetSettings
---@field public enableTranscoding bool
---@field public codec number
---@field public resizeMode number
---@field public aspectRatio number
---@field public customWidth number
---@field public customHeight number
---@field public bitrateMode number
---@field public spatialQuality number
