---@class FullScreenMode : Enum
---@field public value__ number
---@field public ExclusiveFullScreen number
---@field public FullScreenWindow number
---@field public MaximizedWindow number
---@field public Windowed number
