---@class FontRenderingMode : Enum
---@field public value__ number
---@field public Smooth number
---@field public HintedSmooth number
---@field public HintedRaster number
---@field public OSDefault number
