---@class PBXCapabilityType
---@field public ApplePay PBXCapabilityType
---@field public AppGroups PBXCapabilityType
---@field public AssociatedDomains PBXCapabilityType
---@field public BackgroundModes PBXCapabilityType
---@field public DataProtection PBXCapabilityType
---@field public GameCenter PBXCapabilityType
---@field public HealthKit PBXCapabilityType
---@field public HomeKit PBXCapabilityType
---@field public iCloud PBXCapabilityType
---@field public InAppPurchase PBXCapabilityType
---@field public InterAppAudio PBXCapabilityType
---@field public KeychainSharing PBXCapabilityType
---@field public Maps PBXCapabilityType
---@field public PersonalVPN PBXCapabilityType
---@field public PushNotifications PBXCapabilityType
---@field public Siri PBXCapabilityType
---@field public Wallet PBXCapabilityType
---@field public WirelessAccessoryConfiguration PBXCapabilityType
---@field public optionalFramework bool
---@field public framework string
---@field public id string
---@field public requiresEntitlements bool
---@public
---@param cap string
---@return PBXCapabilityType
function PBXCapabilityType.StringToPBXCapabilityType(cap) end
