---@class TickStyle
---@field public tickColor SkinnedColor
---@field public labelColor SkinnedColor
---@field public distMin number
---@field public distFull number
---@field public distLabel number
---@field public stubs bool
---@field public centerLabel bool
---@field public unit string
