---@class Annotation : ValueType
---@field public iconEnabled number
---@field public gizmoEnabled number
---@field public flags number
---@field public classID number
---@field public scriptClass string
