---@class iOSPlatformIconKind
---@field public Application PlatformIconKind
---@field public Settings PlatformIconKind
---@field public Notification PlatformIconKind
---@field public Spotlight PlatformIconKind
---@field public Marketing PlatformIconKind
