---@class WebURLs
---@field public unity string
---@field public unityConnect string
---@field public unityForum string
---@field public unityAnswers string
---@field public unityFeedback string
---@field public whatsNewPage string
---@field public betaLandingPage string
---@field public cloudBuildPage string
