---@class ImportPackageItem
---@field public exportedAssetPath string
---@field public destinationAssetPath string
---@field public sourceFolder string
---@field public previewPath string
---@field public guid string
---@field public enabledStatus number
---@field public isFolder bool
---@field public exists bool
---@field public assetChanged bool
---@field public pathConflict bool
---@field public projectAsset bool
