---@class GUISettings
---@field public doubleClickSelectsWord bool
---@field public tripleClickSelectsLine bool
---@field public cursorColor Color
---@field public cursorFlashSpeed number
---@field public selectionColor Color
