---@class BatteryStatus : Enum
---@field public value__ number
---@field public Unknown number
---@field public Charging number
---@field public Discharging number
---@field public NotCharging number
---@field public Full number
