---@class UnityConnectSettings : Object
---@field public enabled bool
---@field public testMode bool
---@field public testEventUrl string
---@field public testConfigUrl string
---@field public testInitMode number
