---@class ParticleSystemGradientMode : Enum
---@field public value__ number
---@field public Color number
---@field public Gradient number
---@field public TwoColors number
---@field public TwoGradients number
---@field public RandomColor number
