---@class iOSShowActivityIndicatorOnLoading : Enum
---@field public value__ number
---@field public WhiteLarge number
---@field public White number
---@field public Gray number
---@field public DontShow number
