---@class CompressionLevel : Enum
---@field public value__ number
---@field public None number
---@field public Fastest number
---@field public Fast number
---@field public Normal number
---@field public High number
---@field public Maximum number
