---@class MsgType
---@field public ObjectDestroy number
---@field public Rpc number
---@field public ObjectSpawn number
---@field public Owner number
---@field public Command number
---@field public LocalPlayerTransform number
---@field public SyncEvent number
---@field public UpdateVars number
---@field public SyncList number
---@field public ObjectSpawnScene number
---@field public NetworkInfo number
---@field public SpawnFinished number
---@field public ObjectHide number
---@field public CRC number
---@field public LocalClientAuthority number
---@field public LocalChildTransform number
---@field public Fragment number
---@field public PeerClientAuthority number
---@field public InternalHighest number
---@field public Connect number
---@field public Disconnect number
---@field public Error number
---@field public Ready number
---@field public NotReady number
---@field public AddPlayer number
---@field public RemovePlayer number
---@field public Scene number
---@field public Animation number
---@field public AnimationParameters number
---@field public AnimationTrigger number
---@field public LobbyReadyToBegin number
---@field public LobbySceneLoaded number
---@field public LobbyAddPlayerFailed number
---@field public LobbyReturnToLobby number
---@field public ReconnectPlayer number
---@field public Highest number
---@public
---@param value number
---@return string
function MsgType.MsgTypeToString(value) end
