---@class InteractionSourceFlags : Enum
---@field public value__ number
---@field public None number
---@field public SupportsTouchpad number
---@field public SupportsThumbstick number
---@field public SupportsPointing number
---@field public SupportsGrasp number
---@field public SupportsMenu number
