---@class TreeInstance : ValueType
---@field public position Vector3
---@field public widthScale number
---@field public heightScale number
---@field public rotation number
---@field public color Color32
---@field public lightmapColor Color32
---@field public prototypeIndex number
