---@class SystemGestureDeferMode : Enum
---@field public value__ number
---@field public None number
---@field public TopEdge number
---@field public LeftEdge number
---@field public BottomEdge number
---@field public RightEdge number
---@field public All number
