---@class UxmlAttributeDescription
---@field public name string
---@field public type string
---@field public typeNamespace string
---@field public defaultValueAsString string
---@field public use number
---@field public restriction UxmlTypeRestriction
