---@class WSABuildAndRunDeployTarget : Enum
---@field public value__ number
---@field public LocalMachine number
---@field public WindowsPhone number
---@field public LocalMachineAndWindowsPhone number
