---@class BuildState : Enum
---@field public value__ number
---@field public None number
---@field public Configure number
---@field public Success number
---@field public Failed number
---@field public InProgress number
