---@class EnabledOrientation : Enum
---@field public value__ number
---@field public kAutorotateToPortrait number
---@field public kAutorotateToPortraitUpsideDown number
---@field public kAutorotateToLandscapeLeft number
---@field public kAutorotateToLandscapeRight number
