---@class IKeyboardEvent
---@field public modifiers number
---@field public character Char
---@field public keyCode number
---@field public shiftKey bool
---@field public ctrlKey bool
---@field public commandKey bool
---@field public altKey bool
