---@class ParticleSystemShapeMultiModeValue : Enum
---@field public value__ number
---@field public Random number
---@field public Loop number
---@field public PingPong number
---@field public BurstSpread number
