---@class AudioSpatializerExtensionDefinition
---@field public spatializerName PropertyName
---@field public definition AudioExtensionDefinition
---@field public editorDefinition AudioExtensionDefinition
