---@class SplatPrototype
---@field public texture Texture2D
---@field public normalMap Texture2D
---@field public tileSize Vector2
---@field public tileOffset Vector2
---@field public specular Color
---@field public metallic number
---@field public smoothness number
