---@class FrameTiming : ValueType
---@field public cpuTimePresentCalled number
---@field public cpuFrameTime number
---@field public cpuTimeFrameComplete number
---@field public gpuFrameTime number
---@field public heightScale number
---@field public widthScale number
---@field public syncInterval number
