---@class ShaderError : ValueType
---@field public message string
---@field public messageDetails string
---@field public platform string
---@field public file string
---@field public line number
---@field public warning number
