---@class ReflectionProbeUsage : Enum
---@field public value__ number
---@field public Off number
---@field public BlendProbes number
---@field public BlendProbesAndSkybox number
---@field public Simple number
