---@class MemoryRequirement
---@field public Key string
---@field public Any string
---@field public Mem1GB string
---@field public Mem2GB string
---@field public Mem3GB string
---@field public Mem4GB string
