---@class ListViewState
---@field public row number
---@field public column number
---@field public scrollPos Vector2
---@field public totalRows number
---@field public rowHeight number
---@field public ID number
---@field public selectionChanged bool
---@field public draggedFrom number
---@field public draggedTo number
---@field public drawDropHere bool
---@field public dropHereRect Rect
---@field public fileNames String[]
---@field public customDraggedFromID number
