---@class AudioConfiguration : ValueType
---@field public speakerMode number
---@field public dspBufferSize number
---@field public sampleRate number
---@field public numRealVoices number
---@field public numVirtualVoices number
