---@class BuildLaunchPlayerArgs : ValueType
---@field public target number
---@field public playerPackage string
---@field public installPath string
---@field public productName string
---@field public options number
---@field public report BuildReport
