---@class FullScreenMovieScalingMode : Enum
---@field public value__ number
---@field public None number
---@field public AspectFit number
---@field public AspectFill number
---@field public Fill number
