---@class ShaderProperties : ValueType
---@field public floats ShaderFloatInfo[]
---@field public vectors ShaderVectorInfo[]
---@field public matrices ShaderMatrixInfo[]
---@field public textures ShaderTextureInfo[]
---@field public buffers ShaderBufferInfo[]
