---@class DragAndDropVisualMode : Enum
---@field public value__ number
---@field public None number
---@field public Copy number
---@field public Link number
---@field public Move number
---@field public Generic number
---@field public Rejected number
