---@class ChartSeriesViewData
---@field public enabled bool
---@field public name string
---@field public color Color
---@field public xValues Single[]
---@field public yValues Single[]
---@field public rangeAxis Vector2
---@field public numDataPoints number
