---@class AudioSourceCurveType : Enum
---@field public value__ number
---@field public CustomRolloff number
---@field public SpatialBlend number
---@field public ReverbZoneMix number
---@field public Spread number
