---@class AspectRatio : Enum
---@field public value__ number
---@field public AspectOthers number
---@field public Aspect4by3 number
---@field public Aspect5by4 number
---@field public Aspect16by10 number
---@field public Aspect16by9 number
