---@class ParameterTransitionType : Enum
---@field public value__ number
---@field public Lerp number
---@field public Smoothstep number
---@field public Squared number
---@field public SquareRoot number
---@field public BrickwallStart number
---@field public BrickwallEnd number
