---@class FontTextureCase : Enum
---@field public value__ number
---@field public Dynamic number
---@field public Unicode number
---@field public ASCII number
---@field public ASCIIUpperCase number
---@field public ASCIILowerCase number
---@field public CustomSet number
