---@class AssemblyFlags : Enum
---@field public value__ number
---@field public None number
---@field public EditorOnly number
---@field public UseForMono number
---@field public UseForDotNet number
---@field public FirstPass number
---@field public ExcludedForRuntimeCode number
