---@class EnforceJobResult : Enum
---@field public value__ number
---@field public AllJobsAlreadySynced number
---@field public DidSyncRunningJobs number
---@field public HandleWasAlreadyDeallocated number
