---@class ColorBlindCondition : Enum
---@field public value__ number
---@field public Default number
---@field public Deuteranopia number
---@field public Protanopia number
---@field public Tritanopia number
