---@class RenderTargetBinding : ValueType
---@field public colorRenderTargets RenderTargetIdentifier[]
---@field public depthRenderTarget RenderTargetIdentifier
---@field public colorLoadActions RenderBufferLoadAction[]
---@field public colorStoreActions RenderBufferStoreAction[]
---@field public depthLoadAction number
---@field public depthStoreAction number
