---@class IvyArtifactType : Enum
---@field public value__ number
---@field public None number
---@field public Package number
---@field public Ivy number
---@field public Dll number
---@field public ReleaseNotes number
---@field public DebugSymbols number
