---@class GendarmeRuleData
---@field public LastIndex number
---@field public Line number
---@field public File string
---@field public Problem string
---@field public Details string
---@field public Severity string
---@field public Source string
---@field public Location string
---@field public Target string
---@field public IsAssemblyError bool
