---@class NetworkReachability : Enum
---@field public value__ number
---@field public NotReachable number
---@field public ReachableViaCarrierDataNetwork number
---@field public ReachableViaLocalAreaNetwork number
