---@class CreateMatchResponse : BasicResponse
---@field public address string
---@field public port number
---@field public domain number
---@field public networkId number
---@field public accessTokenString string
---@field public nodeId number
---@field public usingRelay bool
---@public
---@return string
function CreateMatchResponse:ToString() end
