---@class PlayerLoopSystemInternal : ValueType
---@field public type Type
---@field public updateDelegate UpdateFunction
---@field public updateFunction IntPtr
---@field public loopConditionFunction IntPtr
---@field public numSubSystems number
