---@class NativeStatusCode : Enum
---@field public value__ number
---@field public InQueue number
---@field public InProgress number
---@field public Done number
---@field public Error number
---@field public NotFound number
---@field public Cancelled number
