---@class Change
---@field public path string
---@field public state number
---@field public isRevertable bool
---@field public revertableState number
---@field public relatedTo string
---@field public isMeta bool
---@field public isConflict bool
---@field public isFolderMeta bool
---@field public isResolved bool
---@field public localStatus string
---@field public remoteStatus string
---@field public resolveStatus string
