---@class ColliderDistance2D : ValueType
---@field public pointA Vector2
---@field public pointB Vector2
---@field public normal Vector2
---@field public distance number
---@field public isOverlapped bool
---@field public isValid bool
