---@class EditorAnalyticsSessionInfo
---@field public id number
---@field public elapsedTime number
---@field public focusedElapsedTime number
---@field public playbackElapsedTime number
---@field public activeElapsedTime number
---@field public userId string
