---@class Navigation : ValueType
---@field public mode number
---@field public selectOnUp Selectable
---@field public selectOnDown Selectable
---@field public selectOnLeft Selectable
---@field public selectOnRight Selectable
---@field public defaultNavigation Navigation
---@public
---@param other Navigation
---@return bool
function Navigation:Equals(other) end
