---@class ScriptAssemblySettings
---@field public BuildTarget number
---@field public BuildTargetGroup number
---@field public OutputDirectory string
---@field public Defines String[]
---@field public ApiCompatibilityLevel number
---@field public CompilationOptions number
---@field public PredefinedAssembliesCompilerOptions ScriptCompilerOptions
---@field public OptionalUnityReferences number
---@field public FilenameSuffix string
---@field public BuildingForEditor bool
---@field public BuildingDevelopmentBuild bool
