---@class FullScreenMovieControlMode : Enum
---@field public value__ number
---@field public Full number
---@field public Minimal number
---@field public CancelOnInput number
---@field public Hidden number
