---@class GlobalConfig
---@field public ThreadAwakeTimeout number
---@field public ReactorModel number
---@field public ReactorMaximumReceivedMessages number
---@field public ReactorMaximumSentMessages number
---@field public MaxPacketSize number
---@field public MaxHosts number
---@field public ThreadPoolSize number
---@field public MinTimerTimeout number
---@field public MaxTimerTimeout number
---@field public MinNetSimulatorTimeout number
---@field public MaxNetSimulatorTimeout number
---@field public NetworkEventAvailable Action`1
---@field public ConnectionReadyForSend Action`2
