---@class CrossCompileOptions : Enum
---@field public value__ number
---@field public Dynamic number
---@field public FastICall number
---@field public Static number
---@field public Debugging number
---@field public ExplicitNullChecks number
---@field public LoadSymbols number
