---@class Gyroscope
---@field public rotationRate Vector3
---@field public rotationRateUnbiased Vector3
---@field public gravity Vector3
---@field public userAcceleration Vector3
---@field public attitude Quaternion
---@field public enabled bool
---@field public updateInterval number
