---@class NativeMethodAttribute : Attribute
---@field public Name string
---@field public IsThreadSafe bool
---@field public IsFreeFunction bool
---@field public ThrowsException bool
---@field public HasExplicitThis bool
---@field public WritableSelf bool
