---@class TexGenMode : Enum
---@field public value__ number
---@field public None number
---@field public SphereMap number
---@field public Object number
---@field public EyeLinear number
---@field public CubeReflect number
---@field public CubeNormal number
