---@class AudioGroupTreeViewGUI : TreeViewGUI
---@field public NodeWasToggled Action`2
---@field public m_Controller AudioMixerController
---@public
---@param rowRect Rect
---@param node TreeViewItem
---@param row number
---@param selected bool
---@param focused bool
---@return void
function AudioGroupTreeViewGUI:OnRowGUI(rowRect, node, row, selected, focused) end
