---@class ScriptChangesDuringPlayOptions : Enum
---@field public value__ number
---@field public RecompileAndContinuePlaying number
---@field public RecompileAfterFinishedPlaying number
---@field public StopPlayingAndRecompile number
