---@class AnalyticsSessionState : Enum
---@field public value__ number
---@field public kSessionStopped number
---@field public kSessionStarted number
---@field public kSessionPaused number
---@field public kSessionResumed number
