---@class CopyTextureSupport : Enum
---@field public value__ number
---@field public None number
---@field public Basic number
---@field public Copy3D number
---@field public DifferentTypes number
---@field public TextureToRT number
---@field public RTToTexture number
