---@class RasterState : ValueType
---@field public Default RasterState
---@field public cullingMode number
---@field public depthClip bool
---@field public offsetUnits number
---@field public offsetFactor number
