---@class TerrainChangedFlags : Enum
---@field public value__ number
---@field public Heightmap number
---@field public TreeInstances number
---@field public DelayedHeightmapUpdate number
---@field public FlushEverythingImmediately number
---@field public RemoveDirtyDetailsImmediately number
---@field public WillBeDestroyed number
