---@class StyleValueType : Enum
---@field public value__ number
---@field public Keyword number
---@field public Float number
---@field public Color number
---@field public ResourcePath number
---@field public Enum number
---@field public String number
