---@class PBXSourceTree : Enum
---@field public value__ number
---@field public Absolute number
---@field public Source number
---@field public Group number
---@field public Build number
---@field public Developer number
---@field public Sdk number
