---@class InteractionSourcePressType : Enum
---@field public value__ number
---@field public None number
---@field public Select number
---@field public Menu number
---@field public Grasp number
---@field public Touchpad number
---@field public Thumbstick number
