---@class ISelectionBinding
---@field public rootGameObject GameObject
---@field public animationClip AnimationClip
---@field public clipIsEditable bool
---@field public animationIsEditable bool
---@field public id number
