---@class ForceReserializeAssetsOptions : Enum
---@field public value__ number
---@field public ReserializeAssets number
---@field public ReserializeMetadata number
---@field public ReserializeAssetsAndMetadata number
