---@class PackageStatus : Enum
---@field public value__ number
---@field public Unknown number
---@field public Unavailable number
---@field public InProgress number
---@field public Error number
---@field public Available number
