---@class AnimatorControllerParameterType : Enum
---@field public value__ number
---@field public Float number
---@field public Int number
---@field public Bool number
---@field public Trigger number
