---@class ObjectMemoryStackInfo
---@field public expanded bool
---@field public sorted bool
---@field public allocated number
---@field public ownedAllocated number
---@field public callerSites ObjectMemoryStackInfo[]
---@field public name string
