---@class TreeViewState
---@field public scrollPos Vector2
---@field public selectedIDs List`1
---@field public lastClickedID number
---@field public expandedIDs List`1
---@field public searchString string
