---@class ParticleCollisionEvent : ValueType
---@field public intersection Vector3
---@field public normal Vector3
---@field public velocity Vector3
---@field public colliderComponent Component
---@field public collider Component
