---@class HighlightSearchMode : Enum
---@field public value__ number
---@field public None number
---@field public Auto number
---@field public Identifier number
---@field public PrefixLabel number
---@field public Content number
