---@class ApplicationInstallMode : Enum
---@field public value__ number
---@field public Unknown number
---@field public Store number
---@field public DeveloperBuild number
---@field public Adhoc number
---@field public Enterprise number
---@field public Editor number
