---@class CompilerMessage : ValueType
---@field public message string
---@field public file string
---@field public line number
---@field public column number
---@field public type number
---@field public normalizedStatus NormalizedCompilerStatus
