---@class ReflectionMethodsCache
---@field public raycast3D Raycast3DCallback
---@field public raycast3DAll RaycastAllCallback
---@field public raycast2D Raycast2DCallback
---@field public getRayIntersectionAll GetRayIntersectionAllCallback
---@field public getRayIntersectionAllNonAlloc GetRayIntersectionAllNonAllocCallback
---@field public getRaycastNonAlloc GetRaycastNonAllocCallback
---@field public Singleton ReflectionMethodsCache
