---@class DrawGridParameters : ValueType
---@field public pivot Vector3
---@field public color Color
---@field public size number
---@field public alphaX number
---@field public alphaY number
---@field public alphaZ number
