---@class InteractionSourceProperties : ValueType
---@field public sourceLossRisk number
---@field public sourceLossMitigationDirection Vector3
---@field public location InteractionSourceLocation
---@field public sourcePose InteractionSourcePose
