---@class MacFullscreenMode : Enum
---@field public value__ number
---@field public CaptureDisplay number
---@field public FullscreenWindow number
---@field public FullscreenWindowWithDockAndMenuBar number
