---@class PropagationPhase : Enum
---@field public value__ number
---@field public None number
---@field public Capture number
---@field public AtTarget number
---@field public BubbleUp number
---@field public DefaultAction number
