---@class AndroidArchitecture : Enum
---@field public value__ number
---@field public None number
---@field public ARMv7 number
---@field public ARM64 number
---@field public X86 number
---@field public All number
