---@class YogaJustify : Enum
---@field public value__ number
---@field public FlexStart number
---@field public Center number
---@field public FlexEnd number
---@field public SpaceBetween number
---@field public SpaceAround number
