---@class ParticleSystemStyles
---@field public label GUIStyle
---@field public editableLabel GUIStyle
---@field public objectField GUIStyle
---@field public numberField GUIStyle
---@field public moduleHeaderStyle GUIStyle
---@field public popup GUIStyle
---@field public emitterHeaderStyle GUIStyle
---@field public effectBgStyle GUIStyle
---@field public moduleBgStyle GUIStyle
---@field public plus GUIStyle
---@field public minus GUIStyle
---@field public checkmark GUIStyle
---@field public checkmarkMixed GUIStyle
---@field public minMaxCurveStateDropDown GUIStyle
---@field public toggle GUIStyle
---@field public toggleMixed GUIStyle
---@field public selectionMarker GUIStyle
---@field public toolbarButtonLeftAlignText GUIStyle
---@field public modulePadding GUIStyle
---@field public warningIcon Texture2D
---@public
---@return ParticleSystemStyles
function ParticleSystemStyles.Get() end
