---@class MoveDirection : Enum
---@field public value__ number
---@field public Left number
---@field public Up number
---@field public Right number
---@field public Down number
---@field public None number
