---@class TouchPhase : Enum
---@field public value__ number
---@field public Began number
---@field public Moved number
---@field public Stationary number
---@field public Ended number
---@field public Canceled number
