---@class LightEvent : Enum
---@field public value__ number
---@field public BeforeShadowMap number
---@field public AfterShadowMap number
---@field public BeforeScreenspaceMask number
---@field public AfterScreenspaceMask number
---@field public BeforeShadowMapPass number
---@field public AfterShadowMapPass number
