---@class PackageSource : Enum
---@field public value__ number
---@field public Unknown number
---@field public Registry number
---@field public BuiltIn number
---@field public Embedded number
---@field public Local number
---@field public Git number
