---@class AnimationCullingType : Enum
---@field public value__ number
---@field public AlwaysAnimate number
---@field public BasedOnRenderers number
---@field public BasedOnClipBounds number
---@field public BasedOnUserBounds number
