---@class BuildPlatform
---@field public name string
---@field public title GUIContent
---@field public smallIcon Texture2D
---@field public targetGroup number
---@field public forceShowTarget bool
---@field public tooltip string
---@field public defaultTarget number
