---@class LogEntry
---@field public condition string
---@field public errorNum number
---@field public file string
---@field public line number
---@field public mode number
---@field public instanceID number
---@field public identifier number
---@field public isWorldPlaying number
