---@class SpritePackingRotation : Enum
---@field public value__ number
---@field public None number
---@field public FlipHorizontal number
---@field public FlipVertical number
---@field public Rotate180 number
---@field public Any number
