---@class Slider2D
---@public
---@param id number
---@param handlePos Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param drawFunc DrawCapFunction
---@param snap number
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, handleDir, slideDir1, slideDir2, handleSize, drawFunc, snap, drawHelper) end
---@public
---@param id number
---@param handlePos Vector3
---@param offset Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param drawFunc DrawCapFunction
---@param snap number
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, offset, handleDir, slideDir1, slideDir2, handleSize, drawFunc, snap, drawHelper) end
---@public
---@param id number
---@param handlePos Vector3
---@param offset Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param drawFunc DrawCapFunction
---@param snap Vector2
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, offset, handleDir, slideDir1, slideDir2, handleSize, drawFunc, snap, drawHelper) end
---@public
---@param id number
---@param handlePos Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param capFunction CapFunction
---@param snap number
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, handleDir, slideDir1, slideDir2, handleSize, capFunction, snap, drawHelper) end
---@public
---@param id number
---@param handlePos Vector3
---@param offset Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param capFunction CapFunction
---@param snap number
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, offset, handleDir, slideDir1, slideDir2, handleSize, capFunction, snap, drawHelper) end
---@public
---@param id number
---@param handlePos Vector3
---@param offset Vector3
---@param handleDir Vector3
---@param slideDir1 Vector3
---@param slideDir2 Vector3
---@param handleSize number
---@param capFunction CapFunction
---@param snap Vector2
---@param drawHelper bool
---@return Vector3
function Slider2D.Do(id, handlePos, offset, handleDir, slideDir1, slideDir2, handleSize, capFunction, snap, drawHelper) end
