---@class DetailPrototype
---@field public prototype GameObject
---@field public prototypeTexture Texture2D
---@field public minWidth number
---@field public maxWidth number
---@field public minHeight number
---@field public maxHeight number
---@field public noiseSpread number
---@field public bendFactor number
---@field public healthyColor Color
---@field public dryColor Color
---@field public renderMode number
---@field public usePrototypeMesh bool
