---@class IMGUIInstruction : ValueType
---@field public type number
---@field public level number
---@field public unclippedRect Rect
---@field public stack StackFrame[]
---@field public typeInstructionIndex number
---@field public enabled bool
