---@class LODParameters : ValueType
---@field public isOrthographic bool
---@field public cameraPosition Vector3
---@field public fieldOfView number
---@field public orthoSize number
---@field public cameraPixelHeight number
