---@class PhysicMaterialCombine : Enum
---@field public value__ number
---@field public Average number
---@field public Minimum number
---@field public Multiply number
---@field public Maximum number
