---@class AndroidETC2FallbackOverride : Enum
---@field public value__ number
---@field public UseBuildSettings number
---@field public Quality32Bit number
---@field public Quality16Bit number
---@field public Quality32BitDownscaled number
