---@class iOSAutomaticallySignValue : Enum
---@field public value__ number
---@field public AutomaticallySignValueNotSet number
---@field public AutomaticallySignValueTrue number
---@field public AutomaticallySignValueFalse number
