---@class ScrollView : VisualElement
---@field public kDefaultScrollerValues Vector2
---@field public stretchContentWidth bool
---@field public horizontalScrollerValues Vector2
---@field public verticalScrollerValues Vector2
---@field public showHorizontal bool
---@field public showVertical bool
---@field public needsHorizontal bool
---@field public needsVertical bool
---@field public scrollOffset Vector2
---@field public contentViewport VisualElement
---@field public contentView VisualElement
---@field public horizontalScroller Scroller
---@field public verticalScroller Scroller
---@field public contentContainer VisualElement
---@public
---@param child VisualElement
---@return void
function ScrollView:ScrollTo(child) end
