---@class PagedListView : VisualElement
---@field public DefaultItemsPerPage number
---@field public pageSize number
---@field public items IEnumerable`1
---@field public totalItems number
---@field public OnPageChanged PageChangeAction
---@field public curPage number
---@field public totalPages number
