---@class Assembly
---@field public name string
---@field public outputPath string
---@field public sourceFiles String[]
---@field public defines String[]
---@field public assemblyReferences Assembly[]
---@field public compiledAssemblyReferences String[]
---@field public flags number
---@field public compilerOptions ScriptCompilerOptions
---@field public allReferences String[]
