---@class CollabSettingType : Enum
---@field public value__ number
---@field public InProgressEnabled number
---@field public InProgressProjectEnabled number
---@field public InProgressGlobalEnabled number
