---@class CameraParameters : ValueType
---@field public hologramOpacity number
---@field public frameRate number
---@field public cameraResolutionWidth number
---@field public cameraResolutionHeight number
---@field public pixelFormat number
