---@class InstrumentedAssemblyTypes : Enum
---@field public value__ number
---@field public None number
---@field public System number
---@field public Unity number
---@field public Plugins number
---@field public Script number
---@field public All number
