---@class ImageData : ValueType
---@field public width number
---@field public height number
---@field public format number
---@field public timestampNs number
---@field public planeData List`1
---@field public planeInfos List`1
---@field public metadata CameraMetadata
