---@class CurveBindingGroup
---@field public curveBindingPairs CurveBindingPair[]
---@field public timeRange Vector2
---@field public valueRange Vector2
---@field public isFloatCurve bool
---@field public isObjectCurve bool
---@field public count number
