---@class JointAngularLimitHandle
---@field public xMin number
---@field public xMax number
---@field public yMin number
---@field public yMax number
---@field public zMin number
---@field public zMax number
---@field public xRange Vector2
---@field public yRange Vector2
---@field public zRange Vector2
---@field public xMotion number
---@field public yMotion number
---@field public zMotion number
---@field public xHandleColor Color
---@field public yHandleColor Color
---@field public zHandleColor Color
---@field public radius number
---@field public fillAlpha number
---@field public wireframeAlpha number
---@field public angleHandleDrawFunction CapFunction
---@field public angleHandleSizeFunction SizeFunction
---@public
---@return void
function JointAngularLimitHandle:DrawHandle() end
