---@class NavigationUpdatedEventArgs : ValueType
---@field public source InteractionSource
---@field public sourcePose InteractionSourcePose
---@field public headPose Pose
---@field public normalizedOffset Vector3
