---@class ApiCompatibilityLevel : Enum
---@field public value__ number
---@field public NET_2_0 number
---@field public NET_2_0_Subset number
---@field public NET_4_6 number
---@field public NET_Web number
---@field public NET_Micro number
---@field public NET_Standard_2_0 number
