---@class LightProbeVisualization
---@field public lightProbeVisualizationMode number
---@field public showInterpolationWeights bool
---@field public showOcclusions bool
---@field public dynamicUpdateLightProbes bool
