---@class PropertyGUIData : ValueType
---@field public property SerializedProperty
---@field public totalPosition Rect
---@field public wasBoldDefaultFont bool
---@field public wasEnabled bool
---@field public color Color
