---@class PlayableBinding : ValueType
---@field public None PlayableBinding[]
---@field public DefaultDuration number
---@field public streamName string
---@field public sourceObject Object
---@field public outputTargetType Type
---@field public sourceBindingType Type
---@field public streamType number
