---@class ObjectInfo
---@field public instanceId number
---@field public memorySize number
---@field public reason number
---@field public referencedBy List`1
---@field public name string
---@field public className string
