---@class SerializationCompletionReason : Enum
---@field public value__ number
---@field public Succeeded number
---@field public NotSupported number
---@field public AccessDenied number
---@field public UnknownError number
