---@class BuildPlayerOptions : ValueType
---@field public scenes String[]
---@field public locationPathName string
---@field public assetBundleManifestPath string
---@field public targetGroup number
---@field public target number
---@field public options number
