---@class SerializedCylinderTarget : SerializedDataSetTrackable
---@field public SideLengthProperty SerializedProperty
---@field public SideLength number
---@field public TopDiameterProperty SerializedProperty
---@field public TopDiameter number
---@field public BottomDiameterProperty SerializedProperty
---@field public BottomDiameter number
---@field public TopDiameterRatioProperty SerializedProperty
---@field public TopDiameterRatio number
---@field public BottomDiameterRatioProperty SerializedProperty
---@field public BottomDiameterRatio number
---@public
---@return List`1
function SerializedCylinderTarget:GetBehaviours() end
