---@class View : Enum
---@field public value__ number
---@field public VIEW_SINGULAR number
---@field public VIEW_LEFTEYE number
---@field public VIEW_RIGHTEYE number
---@field public VIEW_POSTPROCESS number
---@field public VIEW_COUNT number
