---@class ViewerButtonType : Enum
---@field public value__ number
---@field public BUTTON_TYPE_NONE number
---@field public BUTTON_TYPE_MAGNET number
---@field public BUTTON_TYPE_FINGER_TOUCH number
---@field public BUTTON_TYPE_BUTTON_TOUCH number
