---@class CompressionMethod : Enum
---@field public value__ number
---@field public Stored number
---@field public Deflated number
---@field public Deflate64 number
---@field public BZip2 number
---@field public WinZipAES number
