---@class UfoConfiguration
---@field public LICENSE_TYPE_INSTALLATION string
---@field public LICENSE_TYPE_PROJECT string
---@field public UFO_UNIQUE_USER_ID_KEY string
---@field public INSTALLATION_KEY_ID string
---@field public EULA_AGREEMENT_ACCEPTED_VERSIONS string
---@field public SAMPLE_DATASET_PREFIX string
