---@class LookupRequestDTO
---@field public app_name string
---@field public app_version string
---@field public identity_id string
---@field public os_platform string
---@field public sdk_version string
