---@class SerializedImageTarget : SerializedDataSetTrackable
---@field public AspectRatioProperty SerializedProperty
---@field public AspectRatio number
---@field public ImageTargetTypeProperty SerializedProperty
---@field public ImageTargetType number
---@field public WidthProperty SerializedProperty
---@field public Width number
---@field public HeightProperty SerializedProperty
---@field public Height number
---@public
---@return List`1
function SerializedImageTarget:GetBehaviours() end
