---@class SerializedVuMark : SerializedDataSetTrackable
---@field public AspectRatioProperty SerializedProperty
---@field public AspectRatio number
---@field public WidthProperty SerializedProperty
---@field public Width number
---@field public HeightProperty SerializedProperty
---@field public Height number
---@field public PreviewImageProperty SerializedProperty
---@field public PreviewImage string
---@field public IdTypeProperty SerializedProperty
---@field public IdType number
---@field public IdLengthProperty SerializedProperty
---@field public IdLength number
---@field public BoundingBoxProperty SerializedProperty
---@field public BoundingBox Rect
---@field public OriginProperty SerializedProperty
---@field public Origin Vector2
---@field public TrackingFromRuntimeAppearanceProperty SerializedProperty
---@field public TrackingFromRuntimeAppearance bool
---@public
---@return List`1
function SerializedVuMark:GetBehaviours() end
