---@class TestOperation : Enum
---@field public value__ number
---@field public Initialising number
---@field public EntryHeader number
---@field public EntryData number
---@field public EntryComplete number
---@field public MiscellaneousTests number
---@field public Complete number
