---@class PackageData
---@field public PackagePath string
---@field public DialogTitle string
---@field public DialogMessage string
---@field public DialogOk string
---@field public DialogCancel string
