---@class LookupResponseDTO : ValueType
---@field public installer_url string
---@field public latest_version string
---@field public result_code string
---@field public transaction_id string
---@field public upgrade_available bool
---@field public upgrade_message string
