---@class VuforiaConfiguration : ScriptableObject
---@field public Instance VuforiaConfiguration
---@field public Vuforia GenericVuforiaConfiguration
---@field public DigitalEyewear DigitalEyewearConfiguration
---@field public VideoBackground VideoBackgroundConfiguration
---@field public DeviceTracker DeviceTrackerConfiguration
---@field public SmartTerrain SmartTerrainConfiguration
---@field public WebCam WebCamConfiguration
