---@class TestStatus
---@field public Operation number
---@field public File ZipFile
---@field public Entry ZipEntry
---@field public ErrorCount number
---@field public BytesTested number
---@field public EntryValid bool
