---@class ProgressEventArgs : EventArgs
---@field public Name string
---@field public ContinueRunning bool
---@field public PercentComplete number
---@field public Processed number
---@field public Target number
