---@class DefaultDatabaseType : Enum
---@field public value__ number
---@field public ImageTarget number
---@field public MultiTarget number
---@field public CylinderTarget number
---@field public ModelTarget number
---@field public ObjectTarget number
---@field public VuMark number
