---@class LazyMemberTypes : Enum
---@field public value__ number
---@field public Method number
---@field public FieldGet number
---@field public FieldSet number
---@field public PropertyGet number
---@field public PropertySet number
---@field public Event number
